/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkAuthAccessTokensGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkAuthAccessTokensGetResponse{}

// V1NetworkAuthAccessTokensGetResponse struct for V1NetworkAuthAccessTokensGetResponse
type V1NetworkAuthAccessTokensGetResponse struct {
	Data []V1AuthAccessToken `json:"data"`
}

// NewV1NetworkAuthAccessTokensGetResponse instantiates a new V1NetworkAuthAccessTokensGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAccessTokensGetResponse(data []V1AuthAccessToken) *V1NetworkAuthAccessTokensGetResponse {
	this := V1NetworkAuthAccessTokensGetResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAuthAccessTokensGetResponseWithDefaults instantiates a new V1NetworkAuthAccessTokensGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAccessTokensGetResponseWithDefaults() *V1NetworkAuthAccessTokensGetResponse {
	this := V1NetworkAuthAccessTokensGetResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAuthAccessTokensGetResponse) GetData() []V1AuthAccessToken {
	if o == nil {
		var ret []V1AuthAccessToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensGetResponse) GetDataOk() ([]V1AuthAccessToken, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkAuthAccessTokensGetResponse) SetData(v []V1AuthAccessToken) {
	o.Data = v
}

func (o V1NetworkAuthAccessTokensGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkAuthAccessTokensGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkAuthAccessTokensGetResponse struct {
	value *V1NetworkAuthAccessTokensGetResponse
	isSet bool
}

func (v NullableV1NetworkAuthAccessTokensGetResponse) Get() *V1NetworkAuthAccessTokensGetResponse {
	return v.value
}

func (v *NullableV1NetworkAuthAccessTokensGetResponse) Set(val *V1NetworkAuthAccessTokensGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAccessTokensGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAccessTokensGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAccessTokensGetResponse(val *V1NetworkAuthAccessTokensGetResponse) *NullableV1NetworkAuthAccessTokensGetResponse {
	return &NullableV1NetworkAuthAccessTokensGetResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAccessTokensGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAccessTokensGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
