/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1ConnectionService struct for V1ConnectionService
type V1ConnectionService struct {
	AgentConnectionGroupId int32                       `json:"agent_connection_group_id"`
	AgentConnectionSubnets []V1ConnectionServiceSubnet `json:"agent_connection_subnets"`
	Agent2                 V1ConnectionServiceAgent    `json:"agent_2"`
	Agent1                 V1ConnectionServiceAgent    `json:"agent_1"`
}

// NewV1ConnectionService instantiates a new V1ConnectionService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ConnectionService(agentConnectionGroupId int32, agentConnectionSubnets []V1ConnectionServiceSubnet, agent2 V1ConnectionServiceAgent, agent1 V1ConnectionServiceAgent) *V1ConnectionService {
	this := V1ConnectionService{}
	this.AgentConnectionGroupId = agentConnectionGroupId
	this.AgentConnectionSubnets = agentConnectionSubnets
	this.Agent2 = agent2
	this.Agent1 = agent1
	return &this
}

// NewV1ConnectionServiceWithDefaults instantiates a new V1ConnectionService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ConnectionServiceWithDefaults() *V1ConnectionService {
	this := V1ConnectionService{}
	return &this
}

// GetAgentConnectionGroupId returns the AgentConnectionGroupId field value
func (o *V1ConnectionService) GetAgentConnectionGroupId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentConnectionGroupId
}

// GetAgentConnectionGroupIdOk returns a tuple with the AgentConnectionGroupId field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionService) GetAgentConnectionGroupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentConnectionGroupId, true
}

// SetAgentConnectionGroupId sets field value
func (o *V1ConnectionService) SetAgentConnectionGroupId(v int32) {
	o.AgentConnectionGroupId = v
}

// GetAgentConnectionSubnets returns the AgentConnectionSubnets field value
func (o *V1ConnectionService) GetAgentConnectionSubnets() []V1ConnectionServiceSubnet {
	if o == nil {
		var ret []V1ConnectionServiceSubnet
		return ret
	}

	return o.AgentConnectionSubnets
}

// GetAgentConnectionSubnetsOk returns a tuple with the AgentConnectionSubnets field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionService) GetAgentConnectionSubnetsOk() ([]V1ConnectionServiceSubnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentConnectionSubnets, true
}

// SetAgentConnectionSubnets sets field value
func (o *V1ConnectionService) SetAgentConnectionSubnets(v []V1ConnectionServiceSubnet) {
	o.AgentConnectionSubnets = v
}

// GetAgent2 returns the Agent2 field value
func (o *V1ConnectionService) GetAgent2() V1ConnectionServiceAgent {
	if o == nil {
		var ret V1ConnectionServiceAgent
		return ret
	}

	return o.Agent2
}

// GetAgent2Ok returns a tuple with the Agent2 field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionService) GetAgent2Ok() (*V1ConnectionServiceAgent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Agent2, true
}

// SetAgent2 sets field value
func (o *V1ConnectionService) SetAgent2(v V1ConnectionServiceAgent) {
	o.Agent2 = v
}

// GetAgent1 returns the Agent1 field value
func (o *V1ConnectionService) GetAgent1() V1ConnectionServiceAgent {
	if o == nil {
		var ret V1ConnectionServiceAgent
		return ret
	}

	return o.Agent1
}

// GetAgent1Ok returns a tuple with the Agent1 field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionService) GetAgent1Ok() (*V1ConnectionServiceAgent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Agent1, true
}

// SetAgent1 sets field value
func (o *V1ConnectionService) SetAgent1(v V1ConnectionServiceAgent) {
	o.Agent1 = v
}

func (o V1ConnectionService) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_connection_group_id"] = o.AgentConnectionGroupId
	}
	if true {
		toSerialize["agent_connection_subnets"] = o.AgentConnectionSubnets
	}
	if true {
		toSerialize["agent_2"] = o.Agent2
	}
	if true {
		toSerialize["agent_1"] = o.Agent1
	}
	return json.Marshal(toSerialize)
}

type NullableV1ConnectionService struct {
	value *V1ConnectionService
	isSet bool
}

func (v NullableV1ConnectionService) Get() *V1ConnectionService {
	return v.value
}

func (v *NullableV1ConnectionService) Set(val *V1ConnectionService) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ConnectionService) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ConnectionService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ConnectionService(val *V1ConnectionService) *NullableV1ConnectionService {
	return &NullableV1ConnectionService{value: val, isSet: true}
}

func (v NullableV1ConnectionService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ConnectionService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
