/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AgentLockedFields struct for AgentLockedFields
type AgentLockedFields struct {
	AgentLocationCountry *bool    `json:"agent_location_country,omitempty"`
	AgentLocationCity    *bool    `json:"agent_location_city,omitempty"`
	AgentLocationLat     *bool    `json:"agent_location_lat,omitempty"`
	AgentLocationLon     *bool    `json:"agent_location_lon,omitempty"`
	AgentProviderName    *bool    `json:"agent_provider_name,omitempty"`
	AgentTags            []string `json:"agent_tags,omitempty"`
	AgentName            *bool    `json:"agent_name,omitempty"`
}

// NewAgentLockedFields instantiates a new AgentLockedFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentLockedFields() *AgentLockedFields {
	this := AgentLockedFields{}
	return &this
}

// NewAgentLockedFieldsWithDefaults instantiates a new AgentLockedFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentLockedFieldsWithDefaults() *AgentLockedFields {
	this := AgentLockedFields{}
	return &this
}

// GetAgentLocationCountry returns the AgentLocationCountry field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentLocationCountry() bool {
	if o == nil || o.AgentLocationCountry == nil {
		var ret bool
		return ret
	}
	return *o.AgentLocationCountry
}

// GetAgentLocationCountryOk returns a tuple with the AgentLocationCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentLocationCountryOk() (*bool, bool) {
	if o == nil || o.AgentLocationCountry == nil {
		return nil, false
	}
	return o.AgentLocationCountry, true
}

// HasAgentLocationCountry returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentLocationCountry() bool {
	if o != nil && o.AgentLocationCountry != nil {
		return true
	}

	return false
}

// SetAgentLocationCountry gets a reference to the given bool and assigns it to the AgentLocationCountry field.
func (o *AgentLockedFields) SetAgentLocationCountry(v bool) {
	o.AgentLocationCountry = &v
}

// GetAgentLocationCity returns the AgentLocationCity field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentLocationCity() bool {
	if o == nil || o.AgentLocationCity == nil {
		var ret bool
		return ret
	}
	return *o.AgentLocationCity
}

// GetAgentLocationCityOk returns a tuple with the AgentLocationCity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentLocationCityOk() (*bool, bool) {
	if o == nil || o.AgentLocationCity == nil {
		return nil, false
	}
	return o.AgentLocationCity, true
}

// HasAgentLocationCity returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentLocationCity() bool {
	if o != nil && o.AgentLocationCity != nil {
		return true
	}

	return false
}

// SetAgentLocationCity gets a reference to the given bool and assigns it to the AgentLocationCity field.
func (o *AgentLockedFields) SetAgentLocationCity(v bool) {
	o.AgentLocationCity = &v
}

// GetAgentLocationLat returns the AgentLocationLat field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentLocationLat() bool {
	if o == nil || o.AgentLocationLat == nil {
		var ret bool
		return ret
	}
	return *o.AgentLocationLat
}

// GetAgentLocationLatOk returns a tuple with the AgentLocationLat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentLocationLatOk() (*bool, bool) {
	if o == nil || o.AgentLocationLat == nil {
		return nil, false
	}
	return o.AgentLocationLat, true
}

// HasAgentLocationLat returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentLocationLat() bool {
	if o != nil && o.AgentLocationLat != nil {
		return true
	}

	return false
}

// SetAgentLocationLat gets a reference to the given bool and assigns it to the AgentLocationLat field.
func (o *AgentLockedFields) SetAgentLocationLat(v bool) {
	o.AgentLocationLat = &v
}

// GetAgentLocationLon returns the AgentLocationLon field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentLocationLon() bool {
	if o == nil || o.AgentLocationLon == nil {
		var ret bool
		return ret
	}
	return *o.AgentLocationLon
}

// GetAgentLocationLonOk returns a tuple with the AgentLocationLon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentLocationLonOk() (*bool, bool) {
	if o == nil || o.AgentLocationLon == nil {
		return nil, false
	}
	return o.AgentLocationLon, true
}

// HasAgentLocationLon returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentLocationLon() bool {
	if o != nil && o.AgentLocationLon != nil {
		return true
	}

	return false
}

// SetAgentLocationLon gets a reference to the given bool and assigns it to the AgentLocationLon field.
func (o *AgentLockedFields) SetAgentLocationLon(v bool) {
	o.AgentLocationLon = &v
}

// GetAgentProviderName returns the AgentProviderName field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentProviderName() bool {
	if o == nil || o.AgentProviderName == nil {
		var ret bool
		return ret
	}
	return *o.AgentProviderName
}

// GetAgentProviderNameOk returns a tuple with the AgentProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentProviderNameOk() (*bool, bool) {
	if o == nil || o.AgentProviderName == nil {
		return nil, false
	}
	return o.AgentProviderName, true
}

// HasAgentProviderName returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentProviderName() bool {
	if o != nil && o.AgentProviderName != nil {
		return true
	}

	return false
}

// SetAgentProviderName gets a reference to the given bool and assigns it to the AgentProviderName field.
func (o *AgentLockedFields) SetAgentProviderName(v bool) {
	o.AgentProviderName = &v
}

// GetAgentTags returns the AgentTags field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentTags() []string {
	if o == nil || o.AgentTags == nil {
		var ret []string
		return ret
	}
	return o.AgentTags
}

// GetAgentTagsOk returns a tuple with the AgentTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentTagsOk() ([]string, bool) {
	if o == nil || o.AgentTags == nil {
		return nil, false
	}
	return o.AgentTags, true
}

// HasAgentTags returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentTags() bool {
	if o != nil && o.AgentTags != nil {
		return true
	}

	return false
}

// SetAgentTags gets a reference to the given []string and assigns it to the AgentTags field.
func (o *AgentLockedFields) SetAgentTags(v []string) {
	o.AgentTags = v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *AgentLockedFields) GetAgentName() bool {
	if o == nil || o.AgentName == nil {
		var ret bool
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentLockedFields) GetAgentNameOk() (*bool, bool) {
	if o == nil || o.AgentName == nil {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *AgentLockedFields) HasAgentName() bool {
	if o != nil && o.AgentName != nil {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given bool and assigns it to the AgentName field.
func (o *AgentLockedFields) SetAgentName(v bool) {
	o.AgentName = &v
}

func (o AgentLockedFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentLocationCountry != nil {
		toSerialize["agent_location_country"] = o.AgentLocationCountry
	}
	if o.AgentLocationCity != nil {
		toSerialize["agent_location_city"] = o.AgentLocationCity
	}
	if o.AgentLocationLat != nil {
		toSerialize["agent_location_lat"] = o.AgentLocationLat
	}
	if o.AgentLocationLon != nil {
		toSerialize["agent_location_lon"] = o.AgentLocationLon
	}
	if o.AgentProviderName != nil {
		toSerialize["agent_provider_name"] = o.AgentProviderName
	}
	if o.AgentTags != nil {
		toSerialize["agent_tags"] = o.AgentTags
	}
	if o.AgentName != nil {
		toSerialize["agent_name"] = o.AgentName
	}
	return json.Marshal(toSerialize)
}

type NullableAgentLockedFields struct {
	value *AgentLockedFields
	isSet bool
}

func (v NullableAgentLockedFields) Get() *AgentLockedFields {
	return v.value
}

func (v *NullableAgentLockedFields) Set(val *AgentLockedFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentLockedFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentLockedFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentLockedFields(val *AgentLockedFields) *NullableAgentLockedFields {
	return &NullableAgentLockedFields{value: val, isSet: true}
}

func (v NullableAgentLockedFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentLockedFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
