/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1AuthAccessTokensCreateItem struct for V1AuthAccessTokensCreateItem
type V1AuthAccessTokensCreateItem struct {
	AccessToken string `json:"access_token"`
}

// NewV1AuthAccessTokensCreateItem instantiates a new V1AuthAccessTokensCreateItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthAccessTokensCreateItem(accessToken string) *V1AuthAccessTokensCreateItem {
	this := V1AuthAccessTokensCreateItem{}
	this.AccessToken = accessToken
	return &this
}

// NewV1AuthAccessTokensCreateItemWithDefaults instantiates a new V1AuthAccessTokensCreateItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthAccessTokensCreateItemWithDefaults() *V1AuthAccessTokensCreateItem {
	this := V1AuthAccessTokensCreateItem{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *V1AuthAccessTokensCreateItem) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessTokensCreateItem) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *V1AuthAccessTokensCreateItem) SetAccessToken(v string) {
	o.AccessToken = v
}

func (o V1AuthAccessTokensCreateItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["access_token"] = o.AccessToken
	}
	return json.Marshal(toSerialize)
}

type NullableV1AuthAccessTokensCreateItem struct {
	value *V1AuthAccessTokensCreateItem
	isSet bool
}

func (v NullableV1AuthAccessTokensCreateItem) Get() *V1AuthAccessTokensCreateItem {
	return v.value
}

func (v *NullableV1AuthAccessTokensCreateItem) Set(val *V1AuthAccessTokensCreateItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthAccessTokensCreateItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthAccessTokensCreateItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthAccessTokensCreateItem(val *V1AuthAccessTokensCreateItem) *NullableV1AuthAccessTokensCreateItem {
	return &NullableV1AuthAccessTokensCreateItem{value: val, isSet: true}
}

func (v NullableV1AuthAccessTokensCreateItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthAccessTokensCreateItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
