/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkAuthAccessTokensCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkAuthAccessTokensCreateResponse{}

// V1NetworkAuthAccessTokensCreateResponse struct for V1NetworkAuthAccessTokensCreateResponse
type V1NetworkAuthAccessTokensCreateResponse struct {
	Data V1AuthAccessTokensCreateItem `json:"data"`
}

// NewV1NetworkAuthAccessTokensCreateResponse instantiates a new V1NetworkAuthAccessTokensCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAccessTokensCreateResponse(data V1AuthAccessTokensCreateItem) *V1NetworkAuthAccessTokensCreateResponse {
	this := V1NetworkAuthAccessTokensCreateResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAuthAccessTokensCreateResponseWithDefaults instantiates a new V1NetworkAuthAccessTokensCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAccessTokensCreateResponseWithDefaults() *V1NetworkAuthAccessTokensCreateResponse {
	this := V1NetworkAuthAccessTokensCreateResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAuthAccessTokensCreateResponse) GetData() V1AuthAccessTokensCreateItem {
	if o == nil {
		var ret V1AuthAccessTokensCreateItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensCreateResponse) GetDataOk() (*V1AuthAccessTokensCreateItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V1NetworkAuthAccessTokensCreateResponse) SetData(v V1AuthAccessTokensCreateItem) {
	o.Data = v
}

func (o V1NetworkAuthAccessTokensCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkAuthAccessTokensCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkAuthAccessTokensCreateResponse struct {
	value *V1NetworkAuthAccessTokensCreateResponse
	isSet bool
}

func (v NullableV1NetworkAuthAccessTokensCreateResponse) Get() *V1NetworkAuthAccessTokensCreateResponse {
	return v.value
}

func (v *NullableV1NetworkAuthAccessTokensCreateResponse) Set(val *V1NetworkAuthAccessTokensCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAccessTokensCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAccessTokensCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAccessTokensCreateResponse(val *V1NetworkAuthAccessTokensCreateResponse) *NullableV1NetworkAuthAccessTokensCreateResponse {
	return &NullableV1NetworkAuthAccessTokensCreateResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAccessTokensCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAccessTokensCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
