/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1NetworkAgentsRemoveRequest struct for V1NetworkAgentsRemoveRequest
type V1NetworkAgentsRemoveRequest struct {
	AgentIds []int32 `json:"agent_ids"`
}

// NewV1NetworkAgentsRemoveRequest instantiates a new V1NetworkAgentsRemoveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAgentsRemoveRequest(agentIds []int32) *V1NetworkAgentsRemoveRequest {
	this := V1NetworkAgentsRemoveRequest{}
	this.AgentIds = agentIds
	return &this
}

// NewV1NetworkAgentsRemoveRequestWithDefaults instantiates a new V1NetworkAgentsRemoveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAgentsRemoveRequestWithDefaults() *V1NetworkAgentsRemoveRequest {
	this := V1NetworkAgentsRemoveRequest{}
	return &this
}

// GetAgentIds returns the AgentIds field value
func (o *V1NetworkAgentsRemoveRequest) GetAgentIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsRemoveRequest) GetAgentIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *V1NetworkAgentsRemoveRequest) SetAgentIds(v []int32) {
	o.AgentIds = v
}

func (o V1NetworkAgentsRemoveRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_ids"] = o.AgentIds
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAgentsRemoveRequest struct {
	value *V1NetworkAgentsRemoveRequest
	isSet bool
}

func (v NullableV1NetworkAgentsRemoveRequest) Get() *V1NetworkAgentsRemoveRequest {
	return v.value
}

func (v *NullableV1NetworkAgentsRemoveRequest) Set(val *V1NetworkAgentsRemoveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAgentsRemoveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAgentsRemoveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAgentsRemoveRequest(val *V1NetworkAgentsRemoveRequest) *NullableV1NetworkAgentsRemoveRequest {
	return &NullableV1NetworkAgentsRemoveRequest{value: val, isSet: true}
}

func (v NullableV1NetworkAgentsRemoveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAgentsRemoveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
