/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1NetworkConnectionsCreateMeshRequestAgentIds struct for V1NetworkConnectionsCreateMeshRequestAgentIds
type V1NetworkConnectionsCreateMeshRequestAgentIds struct {
	AgentId int32 `json:"agent_id"`
}

// NewV1NetworkConnectionsCreateMeshRequestAgentIds instantiates a new V1NetworkConnectionsCreateMeshRequestAgentIds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsCreateMeshRequestAgentIds(agentId int32) *V1NetworkConnectionsCreateMeshRequestAgentIds {
	this := V1NetworkConnectionsCreateMeshRequestAgentIds{}
	this.AgentId = agentId
	return &this
}

// NewV1NetworkConnectionsCreateMeshRequestAgentIdsWithDefaults instantiates a new V1NetworkConnectionsCreateMeshRequestAgentIds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsCreateMeshRequestAgentIdsWithDefaults() *V1NetworkConnectionsCreateMeshRequestAgentIds {
	this := V1NetworkConnectionsCreateMeshRequestAgentIds{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *V1NetworkConnectionsCreateMeshRequestAgentIds) GetAgentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateMeshRequestAgentIds) GetAgentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *V1NetworkConnectionsCreateMeshRequestAgentIds) SetAgentId(v int32) {
	o.AgentId = v
}

func (o V1NetworkConnectionsCreateMeshRequestAgentIds) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_id"] = o.AgentId
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkConnectionsCreateMeshRequestAgentIds struct {
	value *V1NetworkConnectionsCreateMeshRequestAgentIds
	isSet bool
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIds) Get() *V1NetworkConnectionsCreateMeshRequestAgentIds {
	return v.value
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIds) Set(val *V1NetworkConnectionsCreateMeshRequestAgentIds) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIds) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsCreateMeshRequestAgentIds(val *V1NetworkConnectionsCreateMeshRequestAgentIds) *NullableV1NetworkConnectionsCreateMeshRequestAgentIds {
	return &NullableV1NetworkConnectionsCreateMeshRequestAgentIds{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
