/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// AgentServicesUpdateChanges struct for AgentServicesUpdateChanges
type AgentServicesUpdateChanges struct {
	AgentServiceSubnetId int32 `json:"agent_service_subnet_id"`
	IsEnabled            bool  `json:"is_enabled"`
}

// NewAgentServicesUpdateChanges instantiates a new AgentServicesUpdateChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentServicesUpdateChanges(agentServiceSubnetId int32, isEnabled bool) *AgentServicesUpdateChanges {
	this := AgentServicesUpdateChanges{}
	this.AgentServiceSubnetId = agentServiceSubnetId
	this.IsEnabled = isEnabled
	return &this
}

// NewAgentServicesUpdateChangesWithDefaults instantiates a new AgentServicesUpdateChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentServicesUpdateChangesWithDefaults() *AgentServicesUpdateChanges {
	this := AgentServicesUpdateChanges{}
	return &this
}

// GetAgentServiceSubnetId returns the AgentServiceSubnetId field value
func (o *AgentServicesUpdateChanges) GetAgentServiceSubnetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentServiceSubnetId
}

// GetAgentServiceSubnetIdOk returns a tuple with the AgentServiceSubnetId field value
// and a boolean to check if the value has been set.
func (o *AgentServicesUpdateChanges) GetAgentServiceSubnetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServiceSubnetId, true
}

// SetAgentServiceSubnetId sets field value
func (o *AgentServicesUpdateChanges) SetAgentServiceSubnetId(v int32) {
	o.AgentServiceSubnetId = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *AgentServicesUpdateChanges) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *AgentServicesUpdateChanges) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *AgentServicesUpdateChanges) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

func (o AgentServicesUpdateChanges) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_service_subnet_id"] = o.AgentServiceSubnetId
	}
	if true {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableAgentServicesUpdateChanges struct {
	value *AgentServicesUpdateChanges
	isSet bool
}

func (v NullableAgentServicesUpdateChanges) Get() *AgentServicesUpdateChanges {
	return v.value
}

func (v *NullableAgentServicesUpdateChanges) Set(val *AgentServicesUpdateChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentServicesUpdateChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentServicesUpdateChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentServicesUpdateChanges(val *AgentServicesUpdateChanges) *NullableAgentServicesUpdateChanges {
	return &NullableAgentServicesUpdateChanges{value: val, isSet: true}
}

func (v NullableAgentServicesUpdateChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentServicesUpdateChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
