/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1ConnectionCreateItem struct for V1ConnectionCreateItem
type V1ConnectionCreateItem struct {
	Agent1Id               *int32 `json:"agent_1_id,omitempty"`
	Agent2Id               *int32 `json:"agent_2_id,omitempty"`
	AgentConnectionGroupId *int32 `json:"agent_connection_group_id,omitempty"`
}

// NewV1ConnectionCreateItem instantiates a new V1ConnectionCreateItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ConnectionCreateItem() *V1ConnectionCreateItem {
	this := V1ConnectionCreateItem{}
	return &this
}

// NewV1ConnectionCreateItemWithDefaults instantiates a new V1ConnectionCreateItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ConnectionCreateItemWithDefaults() *V1ConnectionCreateItem {
	this := V1ConnectionCreateItem{}
	return &this
}

// GetAgent1Id returns the Agent1Id field value if set, zero value otherwise.
func (o *V1ConnectionCreateItem) GetAgent1Id() int32 {
	if o == nil || o.Agent1Id == nil {
		var ret int32
		return ret
	}
	return *o.Agent1Id
}

// GetAgent1IdOk returns a tuple with the Agent1Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ConnectionCreateItem) GetAgent1IdOk() (*int32, bool) {
	if o == nil || o.Agent1Id == nil {
		return nil, false
	}
	return o.Agent1Id, true
}

// HasAgent1Id returns a boolean if a field has been set.
func (o *V1ConnectionCreateItem) HasAgent1Id() bool {
	if o != nil && o.Agent1Id != nil {
		return true
	}

	return false
}

// SetAgent1Id gets a reference to the given int32 and assigns it to the Agent1Id field.
func (o *V1ConnectionCreateItem) SetAgent1Id(v int32) {
	o.Agent1Id = &v
}

// GetAgent2Id returns the Agent2Id field value if set, zero value otherwise.
func (o *V1ConnectionCreateItem) GetAgent2Id() int32 {
	if o == nil || o.Agent2Id == nil {
		var ret int32
		return ret
	}
	return *o.Agent2Id
}

// GetAgent2IdOk returns a tuple with the Agent2Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ConnectionCreateItem) GetAgent2IdOk() (*int32, bool) {
	if o == nil || o.Agent2Id == nil {
		return nil, false
	}
	return o.Agent2Id, true
}

// HasAgent2Id returns a boolean if a field has been set.
func (o *V1ConnectionCreateItem) HasAgent2Id() bool {
	if o != nil && o.Agent2Id != nil {
		return true
	}

	return false
}

// SetAgent2Id gets a reference to the given int32 and assigns it to the Agent2Id field.
func (o *V1ConnectionCreateItem) SetAgent2Id(v int32) {
	o.Agent2Id = &v
}

// GetAgentConnectionGroupId returns the AgentConnectionGroupId field value if set, zero value otherwise.
func (o *V1ConnectionCreateItem) GetAgentConnectionGroupId() int32 {
	if o == nil || o.AgentConnectionGroupId == nil {
		var ret int32
		return ret
	}
	return *o.AgentConnectionGroupId
}

// GetAgentConnectionGroupIdOk returns a tuple with the AgentConnectionGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ConnectionCreateItem) GetAgentConnectionGroupIdOk() (*int32, bool) {
	if o == nil || o.AgentConnectionGroupId == nil {
		return nil, false
	}
	return o.AgentConnectionGroupId, true
}

// HasAgentConnectionGroupId returns a boolean if a field has been set.
func (o *V1ConnectionCreateItem) HasAgentConnectionGroupId() bool {
	if o != nil && o.AgentConnectionGroupId != nil {
		return true
	}

	return false
}

// SetAgentConnectionGroupId gets a reference to the given int32 and assigns it to the AgentConnectionGroupId field.
func (o *V1ConnectionCreateItem) SetAgentConnectionGroupId(v int32) {
	o.AgentConnectionGroupId = &v
}

func (o V1ConnectionCreateItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agent1Id != nil {
		toSerialize["agent_1_id"] = o.Agent1Id
	}
	if o.Agent2Id != nil {
		toSerialize["agent_2_id"] = o.Agent2Id
	}
	if o.AgentConnectionGroupId != nil {
		toSerialize["agent_connection_group_id"] = o.AgentConnectionGroupId
	}
	return json.Marshal(toSerialize)
}

type NullableV1ConnectionCreateItem struct {
	value *V1ConnectionCreateItem
	isSet bool
}

func (v NullableV1ConnectionCreateItem) Get() *V1ConnectionCreateItem {
	return v.value
}

func (v *NullableV1ConnectionCreateItem) Set(val *V1ConnectionCreateItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ConnectionCreateItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ConnectionCreateItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ConnectionCreateItem(val *V1ConnectionCreateItem) *NullableV1ConnectionCreateItem {
	return &NullableV1ConnectionCreateItem{value: val, isSet: true}
}

func (v NullableV1ConnectionCreateItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ConnectionCreateItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
