/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1NetworkAgentsSearchRequest struct for V1NetworkAgentsSearchRequest
type V1NetworkAgentsSearchRequest struct {
	Filter *V1AgentFilter                        `json:"filter,omitempty"`
	Order  []AnyOfobjectobjectobjectobjectobject `json:"order,omitempty"`
	// Skip number of items.
	Skip *int32 `json:"skip,omitempty"`
	// Limit returned values count.
	Take   *int32  `json:"take,omitempty"`
	Search *string `json:"search,omitempty"`
}

// NewV1NetworkAgentsSearchRequest instantiates a new V1NetworkAgentsSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAgentsSearchRequest() *V1NetworkAgentsSearchRequest {
	this := V1NetworkAgentsSearchRequest{}
	var skip int32 = 0
	this.Skip = &skip
	var take int32 = 20
	this.Take = &take
	return &this
}

// NewV1NetworkAgentsSearchRequestWithDefaults instantiates a new V1NetworkAgentsSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAgentsSearchRequestWithDefaults() *V1NetworkAgentsSearchRequest {
	this := V1NetworkAgentsSearchRequest{}
	var skip int32 = 0
	this.Skip = &skip
	var take int32 = 20
	this.Take = &take
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *V1NetworkAgentsSearchRequest) GetFilter() V1AgentFilter {
	if o == nil || o.Filter == nil {
		var ret V1AgentFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchRequest) GetFilterOk() (*V1AgentFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *V1NetworkAgentsSearchRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given V1AgentFilter and assigns it to the Filter field.
func (o *V1NetworkAgentsSearchRequest) SetFilter(v V1AgentFilter) {
	o.Filter = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *V1NetworkAgentsSearchRequest) GetOrder() []AnyOfobjectobjectobjectobjectobject {
	if o == nil || o.Order == nil {
		var ret []AnyOfobjectobjectobjectobjectobject
		return ret
	}
	return o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchRequest) GetOrderOk() ([]AnyOfobjectobjectobjectobjectobject, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *V1NetworkAgentsSearchRequest) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given []AnyOfobjectobjectobjectobjectobject and assigns it to the Order field.
func (o *V1NetworkAgentsSearchRequest) SetOrder(v []AnyOfobjectobjectobjectobjectobject) {
	o.Order = v
}

// GetSkip returns the Skip field value if set, zero value otherwise.
func (o *V1NetworkAgentsSearchRequest) GetSkip() int32 {
	if o == nil || o.Skip == nil {
		var ret int32
		return ret
	}
	return *o.Skip
}

// GetSkipOk returns a tuple with the Skip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchRequest) GetSkipOk() (*int32, bool) {
	if o == nil || o.Skip == nil {
		return nil, false
	}
	return o.Skip, true
}

// HasSkip returns a boolean if a field has been set.
func (o *V1NetworkAgentsSearchRequest) HasSkip() bool {
	if o != nil && o.Skip != nil {
		return true
	}

	return false
}

// SetSkip gets a reference to the given int32 and assigns it to the Skip field.
func (o *V1NetworkAgentsSearchRequest) SetSkip(v int32) {
	o.Skip = &v
}

// GetTake returns the Take field value if set, zero value otherwise.
func (o *V1NetworkAgentsSearchRequest) GetTake() int32 {
	if o == nil || o.Take == nil {
		var ret int32
		return ret
	}
	return *o.Take
}

// GetTakeOk returns a tuple with the Take field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchRequest) GetTakeOk() (*int32, bool) {
	if o == nil || o.Take == nil {
		return nil, false
	}
	return o.Take, true
}

// HasTake returns a boolean if a field has been set.
func (o *V1NetworkAgentsSearchRequest) HasTake() bool {
	if o != nil && o.Take != nil {
		return true
	}

	return false
}

// SetTake gets a reference to the given int32 and assigns it to the Take field.
func (o *V1NetworkAgentsSearchRequest) SetTake(v int32) {
	o.Take = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *V1NetworkAgentsSearchRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *V1NetworkAgentsSearchRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *V1NetworkAgentsSearchRequest) SetSearch(v string) {
	o.Search = &v
}

func (o V1NetworkAgentsSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.Skip != nil {
		toSerialize["skip"] = o.Skip
	}
	if o.Take != nil {
		toSerialize["take"] = o.Take
	}
	if o.Search != nil {
		toSerialize["search"] = o.Search
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAgentsSearchRequest struct {
	value *V1NetworkAgentsSearchRequest
	isSet bool
}

func (v NullableV1NetworkAgentsSearchRequest) Get() *V1NetworkAgentsSearchRequest {
	return v.value
}

func (v *NullableV1NetworkAgentsSearchRequest) Set(val *V1NetworkAgentsSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAgentsSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAgentsSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAgentsSearchRequest(val *V1NetworkAgentsSearchRequest) *NullableV1NetworkAgentsSearchRequest {
	return &NullableV1NetworkAgentsSearchRequest{value: val, isSet: true}
}

func (v NullableV1NetworkAgentsSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAgentsSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
