/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
	"time"
)

// checks if the V1Agent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1Agent{}

// V1Agent struct for V1Agent
type V1Agent struct {
	AgentId                          int32                  `json:"agent_id"`
	AgentPublicIpv4                  string                 `json:"agent_public_ipv4"`
	AgentLocationCity                NullableString         `json:"agent_location_city"`
	AgentDeviceId                    string                 `json:"agent_device_id"`
	AgentName                        string                 `json:"agent_name"`
	AgentStatus                      NullableAgentStatus    `json:"agent_status"`
	AgentVersion                     string                 `json:"agent_version"`
	AgentLockedFields                AgentLockedFields      `json:"agent_locked_fields"`
	AgentModifiedAt                  time.Time              `json:"agent_modified_at"`
	AgentIsVirtual                   bool                   `json:"agent_is_virtual"`
	AgentType                        AgentType              `json:"agent_type"`
	AgentProvider                    AgentProviderNameAndId `json:"agent_provider"`
	AgentTags                        []AgentTag             `json:"agent_tags"`
	AgentServicesSubnetsEnabledCount int32                  `json:"agent_services_subnets_enabled_count"`
	AgentServicesSubnetsCount        int32                  `json:"agent_services_subnets_count"`
	AgentLocationCountry             NullableString         `json:"agent_location_country"`
	AgentIsOnline                    bool                   `json:"agent_is_online"`
}

// NewV1Agent instantiates a new V1Agent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Agent(agentId int32, agentPublicIpv4 string, agentLocationCity NullableString, agentDeviceId string, agentName string, agentStatus NullableAgentStatus, agentVersion string, agentLockedFields AgentLockedFields, agentModifiedAt time.Time, agentIsVirtual bool, agentType AgentType, agentProvider AgentProviderNameAndId, agentTags []AgentTag, agentServicesSubnetsEnabledCount int32, agentServicesSubnetsCount int32, agentLocationCountry NullableString, agentIsOnline bool) *V1Agent {
	this := V1Agent{}
	this.AgentId = agentId
	this.AgentPublicIpv4 = agentPublicIpv4
	this.AgentLocationCity = agentLocationCity
	this.AgentDeviceId = agentDeviceId
	this.AgentName = agentName
	this.AgentStatus = agentStatus
	this.AgentVersion = agentVersion
	this.AgentLockedFields = agentLockedFields
	this.AgentModifiedAt = agentModifiedAt
	this.AgentIsVirtual = agentIsVirtual
	this.AgentType = agentType
	this.AgentProvider = agentProvider
	this.AgentTags = agentTags
	this.AgentServicesSubnetsEnabledCount = agentServicesSubnetsEnabledCount
	this.AgentServicesSubnetsCount = agentServicesSubnetsCount
	this.AgentLocationCountry = agentLocationCountry
	this.AgentIsOnline = agentIsOnline
	return &this
}

// NewV1AgentWithDefaults instantiates a new V1Agent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AgentWithDefaults() *V1Agent {
	this := V1Agent{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *V1Agent) GetAgentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *V1Agent) SetAgentId(v int32) {
	o.AgentId = v
}

// GetAgentPublicIpv4 returns the AgentPublicIpv4 field value
func (o *V1Agent) GetAgentPublicIpv4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentPublicIpv4
}

// GetAgentPublicIpv4Ok returns a tuple with the AgentPublicIpv4 field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentPublicIpv4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentPublicIpv4, true
}

// SetAgentPublicIpv4 sets field value
func (o *V1Agent) SetAgentPublicIpv4(v string) {
	o.AgentPublicIpv4 = v
}

// GetAgentLocationCity returns the AgentLocationCity field value
// If the value is explicit nil, the zero value for string will be returned
func (o *V1Agent) GetAgentLocationCity() string {
	if o == nil || o.AgentLocationCity.Get() == nil {
		var ret string
		return ret
	}

	return *o.AgentLocationCity.Get()
}

// GetAgentLocationCityOk returns a tuple with the AgentLocationCity field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V1Agent) GetAgentLocationCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentLocationCity.Get(), o.AgentLocationCity.IsSet()
}

// SetAgentLocationCity sets field value
func (o *V1Agent) SetAgentLocationCity(v string) {
	o.AgentLocationCity.Set(&v)
}

// GetAgentDeviceId returns the AgentDeviceId field value
func (o *V1Agent) GetAgentDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentDeviceId
}

// GetAgentDeviceIdOk returns a tuple with the AgentDeviceId field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentDeviceId, true
}

// SetAgentDeviceId sets field value
func (o *V1Agent) SetAgentDeviceId(v string) {
	o.AgentDeviceId = v
}

// GetAgentName returns the AgentName field value
func (o *V1Agent) GetAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *V1Agent) SetAgentName(v string) {
	o.AgentName = v
}

// GetAgentStatus returns the AgentStatus field value
// If the value is explicit nil, the zero value for AgentStatus will be returned
func (o *V1Agent) GetAgentStatus() AgentStatusCustom {
	if o == nil || o.AgentStatus.Get() == nil {
		var ret AgentStatusCustom
		return ret
	}

	return *o.AgentStatus.Get()
}

// GetAgentStatusOk returns a tuple with the AgentStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V1Agent) GetAgentStatusOk() (*AgentStatusCustom, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentStatus.Get(), o.AgentStatus.IsSet()
}

// SetAgentStatus sets field value
func (o *V1Agent) SetAgentStatus(v AgentStatusCustom) {
	o.AgentStatus.Set(&v)
}

// GetAgentVersion returns the AgentVersion field value
func (o *V1Agent) GetAgentVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentVersion, true
}

// SetAgentVersion sets field value
func (o *V1Agent) SetAgentVersion(v string) {
	o.AgentVersion = v
}

// GetAgentLockedFields returns the AgentLockedFields field value
func (o *V1Agent) GetAgentLockedFields() AgentLockedFields {
	if o == nil {
		var ret AgentLockedFields
		return ret
	}

	return o.AgentLockedFields
}

// GetAgentLockedFieldsOk returns a tuple with the AgentLockedFields field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentLockedFieldsOk() (*AgentLockedFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentLockedFields, true
}

// SetAgentLockedFields sets field value
func (o *V1Agent) SetAgentLockedFields(v AgentLockedFields) {
	o.AgentLockedFields = v
}

// GetAgentModifiedAt returns the AgentModifiedAt field value
func (o *V1Agent) GetAgentModifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AgentModifiedAt
}

// GetAgentModifiedAtOk returns a tuple with the AgentModifiedAt field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentModifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentModifiedAt, true
}

// SetAgentModifiedAt sets field value
func (o *V1Agent) SetAgentModifiedAt(v time.Time) {
	o.AgentModifiedAt = v
}

// GetAgentIsVirtual returns the AgentIsVirtual field value
func (o *V1Agent) GetAgentIsVirtual() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AgentIsVirtual
}

// GetAgentIsVirtualOk returns a tuple with the AgentIsVirtual field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentIsVirtualOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentIsVirtual, true
}

// SetAgentIsVirtual sets field value
func (o *V1Agent) SetAgentIsVirtual(v bool) {
	o.AgentIsVirtual = v
}

// GetAgentType returns the AgentType field value
func (o *V1Agent) GetAgentType() AgentType {
	if o == nil {
		var ret AgentType
		return ret
	}

	return o.AgentType
}

// GetAgentTypeOk returns a tuple with the AgentType field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentTypeOk() (*AgentType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentType, true
}

// SetAgentType sets field value
func (o *V1Agent) SetAgentType(v AgentType) {
	o.AgentType = v
}

// GetAgentProvider returns the AgentProvider field value
func (o *V1Agent) GetAgentProvider() AgentProviderNameAndId {
	if o == nil {
		var ret AgentProviderNameAndId
		return ret
	}

	return o.AgentProvider
}

// GetAgentProviderOk returns a tuple with the AgentProvider field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentProviderOk() (*AgentProviderNameAndId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentProvider, true
}

// SetAgentProvider sets field value
func (o *V1Agent) SetAgentProvider(v AgentProviderNameAndId) {
	o.AgentProvider = v
}

// GetAgentTags returns the AgentTags field value
func (o *V1Agent) GetAgentTags() []AgentTag {
	if o == nil {
		var ret []AgentTag
		return ret
	}

	return o.AgentTags
}

// GetAgentTagsOk returns a tuple with the AgentTags field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentTagsOk() ([]AgentTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentTags, true
}

// SetAgentTags sets field value
func (o *V1Agent) SetAgentTags(v []AgentTag) {
	o.AgentTags = v
}

// GetAgentServicesSubnetsEnabledCount returns the AgentServicesSubnetsEnabledCount field value
func (o *V1Agent) GetAgentServicesSubnetsEnabledCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentServicesSubnetsEnabledCount
}

// GetAgentServicesSubnetsEnabledCountOk returns a tuple with the AgentServicesSubnetsEnabledCount field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentServicesSubnetsEnabledCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServicesSubnetsEnabledCount, true
}

// SetAgentServicesSubnetsEnabledCount sets field value
func (o *V1Agent) SetAgentServicesSubnetsEnabledCount(v int32) {
	o.AgentServicesSubnetsEnabledCount = v
}

// GetAgentServicesSubnetsCount returns the AgentServicesSubnetsCount field value
func (o *V1Agent) GetAgentServicesSubnetsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentServicesSubnetsCount
}

// GetAgentServicesSubnetsCountOk returns a tuple with the AgentServicesSubnetsCount field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentServicesSubnetsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServicesSubnetsCount, true
}

// SetAgentServicesSubnetsCount sets field value
func (o *V1Agent) SetAgentServicesSubnetsCount(v int32) {
	o.AgentServicesSubnetsCount = v
}

// GetAgentLocationCountry returns the AgentLocationCountry field value
// If the value is explicit nil, the zero value for string will be returned
func (o *V1Agent) GetAgentLocationCountry() string {
	if o == nil || o.AgentLocationCountry.Get() == nil {
		var ret string
		return ret
	}

	return *o.AgentLocationCountry.Get()
}

// GetAgentLocationCountryOk returns a tuple with the AgentLocationCountry field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *V1Agent) GetAgentLocationCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentLocationCountry.Get(), o.AgentLocationCountry.IsSet()
}

// SetAgentLocationCountry sets field value
func (o *V1Agent) SetAgentLocationCountry(v string) {
	o.AgentLocationCountry.Set(&v)
}

// GetAgentIsOnline returns the AgentIsOnline field value
func (o *V1Agent) GetAgentIsOnline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AgentIsOnline
}

// GetAgentIsOnlineOk returns a tuple with the AgentIsOnline field value
// and a boolean to check if the value has been set.
func (o *V1Agent) GetAgentIsOnlineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentIsOnline, true
}

// SetAgentIsOnline sets field value
func (o *V1Agent) SetAgentIsOnline(v bool) {
	o.AgentIsOnline = v
}

func (o V1Agent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1Agent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	toSerialize["agent_public_ipv4"] = o.AgentPublicIpv4
	toSerialize["agent_location_city"] = o.AgentLocationCity.Get()
	toSerialize["agent_device_id"] = o.AgentDeviceId
	toSerialize["agent_name"] = o.AgentName
	toSerialize["agent_status"] = o.AgentStatus.Get()
	toSerialize["agent_version"] = o.AgentVersion
	toSerialize["agent_locked_fields"] = o.AgentLockedFields
	toSerialize["agent_modified_at"] = o.AgentModifiedAt
	toSerialize["agent_is_virtual"] = o.AgentIsVirtual
	toSerialize["agent_type"] = o.AgentType
	toSerialize["agent_provider"] = o.AgentProvider
	toSerialize["agent_tags"] = o.AgentTags
	toSerialize["agent_services_subnets_enabled_count"] = o.AgentServicesSubnetsEnabledCount
	toSerialize["agent_services_subnets_count"] = o.AgentServicesSubnetsCount
	toSerialize["agent_location_country"] = o.AgentLocationCountry.Get()
	toSerialize["agent_is_online"] = o.AgentIsOnline
	return toSerialize, nil
}

type NullableV1Agent struct {
	value *V1Agent
	isSet bool
}

func (v NullableV1Agent) Get() *V1Agent {
	return v.value
}

func (v *NullableV1Agent) Set(val *V1Agent) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Agent) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Agent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Agent(val *V1Agent) *NullableV1Agent {
	return &NullableV1Agent{value: val, isSet: true}
}

func (v NullableV1Agent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Agent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
