/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1AgentOrderInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AgentOrderInnerAnyOf{}

// V1AgentOrderInnerAnyOf struct for V1AgentOrderInnerAnyOf
type V1AgentOrderInnerAnyOf struct {
	AgentName Order `json:"agent_name"`
}

// NewV1AgentOrderInnerAnyOf instantiates a new V1AgentOrderInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AgentOrderInnerAnyOf(agentName Order) *V1AgentOrderInnerAnyOf {
	this := V1AgentOrderInnerAnyOf{}
	this.AgentName = agentName
	return &this
}

// NewV1AgentOrderInnerAnyOfWithDefaults instantiates a new V1AgentOrderInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AgentOrderInnerAnyOfWithDefaults() *V1AgentOrderInnerAnyOf {
	this := V1AgentOrderInnerAnyOf{}
	return &this
}

// GetAgentName returns the AgentName field value
func (o *V1AgentOrderInnerAnyOf) GetAgentName() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value
// and a boolean to check if the value has been set.
func (o *V1AgentOrderInnerAnyOf) GetAgentNameOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentName, true
}

// SetAgentName sets field value
func (o *V1AgentOrderInnerAnyOf) SetAgentName(v Order) {
	o.AgentName = v
}

func (o V1AgentOrderInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AgentOrderInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_name"] = o.AgentName
	return toSerialize, nil
}

type NullableV1AgentOrderInnerAnyOf struct {
	value *V1AgentOrderInnerAnyOf
	isSet bool
}

func (v NullableV1AgentOrderInnerAnyOf) Get() *V1AgentOrderInnerAnyOf {
	return v.value
}

func (v *NullableV1AgentOrderInnerAnyOf) Set(val *V1AgentOrderInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AgentOrderInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AgentOrderInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AgentOrderInnerAnyOf(val *V1AgentOrderInnerAnyOf) *NullableV1AgentOrderInnerAnyOf {
	return &NullableV1AgentOrderInnerAnyOf{value: val, isSet: true}
}

func (v NullableV1AgentOrderInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AgentOrderInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
