/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1AuthAccessToken struct for V1AuthAccessToken
type V1AuthAccessToken struct {
	AccessTokenName        *string `json:"access_token_name,omitempty"`
	AccessTokenExpiration  string  `json:"access_token_expiration"`
	AccessTokenDescription *string `json:"access_token_description,omitempty"`
	AccessTokenId          string  `json:"access_token_id"`
}

// NewV1AuthAccessToken instantiates a new V1AuthAccessToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthAccessToken(accessTokenExpiration string, accessTokenId string) *V1AuthAccessToken {
	this := V1AuthAccessToken{}
	this.AccessTokenExpiration = accessTokenExpiration
	this.AccessTokenId = accessTokenId
	return &this
}

// NewV1AuthAccessTokenWithDefaults instantiates a new V1AuthAccessToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthAccessTokenWithDefaults() *V1AuthAccessToken {
	this := V1AuthAccessToken{}
	return &this
}

// GetAccessTokenName returns the AccessTokenName field value if set, zero value otherwise.
func (o *V1AuthAccessToken) GetAccessTokenName() string {
	if o == nil || o.AccessTokenName == nil {
		var ret string
		return ret
	}
	return *o.AccessTokenName
}

// GetAccessTokenNameOk returns a tuple with the AccessTokenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthAccessToken) GetAccessTokenNameOk() (*string, bool) {
	if o == nil || o.AccessTokenName == nil {
		return nil, false
	}
	return o.AccessTokenName, true
}

// HasAccessTokenName returns a boolean if a field has been set.
func (o *V1AuthAccessToken) HasAccessTokenName() bool {
	if o != nil && o.AccessTokenName != nil {
		return true
	}

	return false
}

// SetAccessTokenName gets a reference to the given string and assigns it to the AccessTokenName field.
func (o *V1AuthAccessToken) SetAccessTokenName(v string) {
	o.AccessTokenName = &v
}

// GetAccessTokenExpiration returns the AccessTokenExpiration field value
func (o *V1AuthAccessToken) GetAccessTokenExpiration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessTokenExpiration
}

// GetAccessTokenExpirationOk returns a tuple with the AccessTokenExpiration field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessToken) GetAccessTokenExpirationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenExpiration, true
}

// SetAccessTokenExpiration sets field value
func (o *V1AuthAccessToken) SetAccessTokenExpiration(v string) {
	o.AccessTokenExpiration = v
}

// GetAccessTokenDescription returns the AccessTokenDescription field value if set, zero value otherwise.
func (o *V1AuthAccessToken) GetAccessTokenDescription() string {
	if o == nil || o.AccessTokenDescription == nil {
		var ret string
		return ret
	}
	return *o.AccessTokenDescription
}

// GetAccessTokenDescriptionOk returns a tuple with the AccessTokenDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthAccessToken) GetAccessTokenDescriptionOk() (*string, bool) {
	if o == nil || o.AccessTokenDescription == nil {
		return nil, false
	}
	return o.AccessTokenDescription, true
}

// HasAccessTokenDescription returns a boolean if a field has been set.
func (o *V1AuthAccessToken) HasAccessTokenDescription() bool {
	if o != nil && o.AccessTokenDescription != nil {
		return true
	}

	return false
}

// SetAccessTokenDescription gets a reference to the given string and assigns it to the AccessTokenDescription field.
func (o *V1AuthAccessToken) SetAccessTokenDescription(v string) {
	o.AccessTokenDescription = &v
}

// GetAccessTokenId returns the AccessTokenId field value
func (o *V1AuthAccessToken) GetAccessTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessTokenId
}

// GetAccessTokenIdOk returns a tuple with the AccessTokenId field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessToken) GetAccessTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenId, true
}

// SetAccessTokenId sets field value
func (o *V1AuthAccessToken) SetAccessTokenId(v string) {
	o.AccessTokenId = v
}

func (o V1AuthAccessToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccessTokenName != nil {
		toSerialize["access_token_name"] = o.AccessTokenName
	}
	if true {
		toSerialize["access_token_expiration"] = o.AccessTokenExpiration
	}
	if o.AccessTokenDescription != nil {
		toSerialize["access_token_description"] = o.AccessTokenDescription
	}
	if true {
		toSerialize["access_token_id"] = o.AccessTokenId
	}
	return json.Marshal(toSerialize)
}

type NullableV1AuthAccessToken struct {
	value *V1AuthAccessToken
	isSet bool
}

func (v NullableV1AuthAccessToken) Get() *V1AuthAccessToken {
	return v.value
}

func (v *NullableV1AuthAccessToken) Set(val *V1AuthAccessToken) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthAccessToken) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthAccessToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthAccessToken(val *V1AuthAccessToken) *NullableV1AuthAccessToken {
	return &NullableV1AuthAccessToken{value: val, isSet: true}
}

func (v NullableV1AuthAccessToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthAccessToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
