/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1AgentOrderInnerAnyOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AgentOrderInnerAnyOf4{}

// V1AgentOrderInnerAnyOf4 struct for V1AgentOrderInnerAnyOf4
type V1AgentOrderInnerAnyOf4 struct {
	AgentModifiedAt Order `json:"agent_modified_at"`
}

// NewV1AgentOrderInnerAnyOf4 instantiates a new V1AgentOrderInnerAnyOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AgentOrderInnerAnyOf4(agentModifiedAt Order) *V1AgentOrderInnerAnyOf4 {
	this := V1AgentOrderInnerAnyOf4{}
	this.AgentModifiedAt = agentModifiedAt
	return &this
}

// NewV1AgentOrderInnerAnyOf4WithDefaults instantiates a new V1AgentOrderInnerAnyOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AgentOrderInnerAnyOf4WithDefaults() *V1AgentOrderInnerAnyOf4 {
	this := V1AgentOrderInnerAnyOf4{}
	return &this
}

// GetAgentModifiedAt returns the AgentModifiedAt field value
func (o *V1AgentOrderInnerAnyOf4) GetAgentModifiedAt() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentModifiedAt
}

// GetAgentModifiedAtOk returns a tuple with the AgentModifiedAt field value
// and a boolean to check if the value has been set.
func (o *V1AgentOrderInnerAnyOf4) GetAgentModifiedAtOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentModifiedAt, true
}

// SetAgentModifiedAt sets field value
func (o *V1AgentOrderInnerAnyOf4) SetAgentModifiedAt(v Order) {
	o.AgentModifiedAt = v
}

func (o V1AgentOrderInnerAnyOf4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AgentOrderInnerAnyOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_modified_at"] = o.AgentModifiedAt
	return toSerialize, nil
}

type NullableV1AgentOrderInnerAnyOf4 struct {
	value *V1AgentOrderInnerAnyOf4
	isSet bool
}

func (v NullableV1AgentOrderInnerAnyOf4) Get() *V1AgentOrderInnerAnyOf4 {
	return v.value
}

func (v *NullableV1AgentOrderInnerAnyOf4) Set(val *V1AgentOrderInnerAnyOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AgentOrderInnerAnyOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AgentOrderInnerAnyOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AgentOrderInnerAnyOf4(val *V1AgentOrderInnerAnyOf4) *NullableV1AgentOrderInnerAnyOf4 {
	return &NullableV1AgentOrderInnerAnyOf4{value: val, isSet: true}
}

func (v NullableV1AgentOrderInnerAnyOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AgentOrderInnerAnyOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
