/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkAgentsSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkAgentsSearchResponse{}

// V1NetworkAgentsSearchResponse struct for V1NetworkAgentsSearchResponse
type V1NetworkAgentsSearchResponse struct {
	Data []V1Agent `json:"data"`
}

// NewV1NetworkAgentsSearchResponse instantiates a new V1NetworkAgentsSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAgentsSearchResponse(data []V1Agent) *V1NetworkAgentsSearchResponse {
	this := V1NetworkAgentsSearchResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAgentsSearchResponseWithDefaults instantiates a new V1NetworkAgentsSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAgentsSearchResponseWithDefaults() *V1NetworkAgentsSearchResponse {
	this := V1NetworkAgentsSearchResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAgentsSearchResponse) GetData() []V1Agent {
	if o == nil {
		var ret []V1Agent
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsSearchResponse) GetDataOk() ([]V1Agent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkAgentsSearchResponse) SetData(v []V1Agent) {
	o.Data = v
}

func (o V1NetworkAgentsSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkAgentsSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkAgentsSearchResponse struct {
	value *V1NetworkAgentsSearchResponse
	isSet bool
}

func (v NullableV1NetworkAgentsSearchResponse) Get() *V1NetworkAgentsSearchResponse {
	return v.value
}

func (v *NullableV1NetworkAgentsSearchResponse) Set(val *V1NetworkAgentsSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAgentsSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAgentsSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAgentsSearchResponse(val *V1NetworkAgentsSearchResponse) *NullableV1NetworkAgentsSearchResponse {
	return &NullableV1NetworkAgentsSearchResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAgentsSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAgentsSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
