/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the AgentInterfaceMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentInterfaceMetadata{}

// AgentInterfaceMetadata struct for AgentInterfaceMetadata
type AgentInterfaceMetadata struct {
	AgentInterfacePublicKey *string `json:"agent_interface_public_key,omitempty"`
}

// NewAgentInterfaceMetadata instantiates a new AgentInterfaceMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentInterfaceMetadata() *AgentInterfaceMetadata {
	this := AgentInterfaceMetadata{}
	return &this
}

// NewAgentInterfaceMetadataWithDefaults instantiates a new AgentInterfaceMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentInterfaceMetadataWithDefaults() *AgentInterfaceMetadata {
	this := AgentInterfaceMetadata{}
	return &this
}

// GetAgentInterfacePublicKey returns the AgentInterfacePublicKey field value if set, zero value otherwise.
func (o *AgentInterfaceMetadata) GetAgentInterfacePublicKey() string {
	if o == nil || isNil(o.AgentInterfacePublicKey) {
		var ret string
		return ret
	}
	return *o.AgentInterfacePublicKey
}

// GetAgentInterfacePublicKeyOk returns a tuple with the AgentInterfacePublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentInterfaceMetadata) GetAgentInterfacePublicKeyOk() (*string, bool) {
	if o == nil || isNil(o.AgentInterfacePublicKey) {
		return nil, false
	}
	return o.AgentInterfacePublicKey, true
}

// HasAgentInterfacePublicKey returns a boolean if a field has been set.
func (o *AgentInterfaceMetadata) HasAgentInterfacePublicKey() bool {
	if o != nil && !isNil(o.AgentInterfacePublicKey) {
		return true
	}

	return false
}

// SetAgentInterfacePublicKey gets a reference to the given string and assigns it to the AgentInterfacePublicKey field.
func (o *AgentInterfaceMetadata) SetAgentInterfacePublicKey(v string) {
	o.AgentInterfacePublicKey = &v
}

func (o AgentInterfaceMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentInterfaceMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AgentInterfacePublicKey) {
		toSerialize["agent_interface_public_key"] = o.AgentInterfacePublicKey
	}
	return toSerialize, nil
}

type NullableAgentInterfaceMetadata struct {
	value *AgentInterfaceMetadata
	isSet bool
}

func (v NullableAgentInterfaceMetadata) Get() *AgentInterfaceMetadata {
	return v.value
}

func (v *NullableAgentInterfaceMetadata) Set(val *AgentInterfaceMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentInterfaceMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentInterfaceMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentInterfaceMetadata(val *AgentInterfaceMetadata) *NullableAgentInterfaceMetadata {
	return &NullableAgentInterfaceMetadata{value: val, isSet: true}
}

func (v NullableAgentInterfaceMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentInterfaceMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
