/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1NetworkConnectionsServicesUpdateRequest struct for V1NetworkConnectionsServicesUpdateRequest
type V1NetworkConnectionsServicesUpdateRequest struct {
	AgentConnectionGroupId *int32                       `json:"agent_connection_group_id,omitempty"`
	Changes                []AgentServicesUpdateChanges `json:"changes"`
}

// NewV1NetworkConnectionsServicesUpdateRequest instantiates a new V1NetworkConnectionsServicesUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsServicesUpdateRequest(changes []AgentServicesUpdateChanges) *V1NetworkConnectionsServicesUpdateRequest {
	this := V1NetworkConnectionsServicesUpdateRequest{}
	this.Changes = changes
	return &this
}

// NewV1NetworkConnectionsServicesUpdateRequestWithDefaults instantiates a new V1NetworkConnectionsServicesUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsServicesUpdateRequestWithDefaults() *V1NetworkConnectionsServicesUpdateRequest {
	this := V1NetworkConnectionsServicesUpdateRequest{}
	return &this
}

// GetAgentConnectionGroupId returns the AgentConnectionGroupId field value if set, zero value otherwise.
func (o *V1NetworkConnectionsServicesUpdateRequest) GetAgentConnectionGroupId() int32 {
	if o == nil || o.AgentConnectionGroupId == nil {
		var ret int32
		return ret
	}
	return *o.AgentConnectionGroupId
}

// GetAgentConnectionGroupIdOk returns a tuple with the AgentConnectionGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsServicesUpdateRequest) GetAgentConnectionGroupIdOk() (*int32, bool) {
	if o == nil || o.AgentConnectionGroupId == nil {
		return nil, false
	}
	return o.AgentConnectionGroupId, true
}

// HasAgentConnectionGroupId returns a boolean if a field has been set.
func (o *V1NetworkConnectionsServicesUpdateRequest) HasAgentConnectionGroupId() bool {
	if o != nil && o.AgentConnectionGroupId != nil {
		return true
	}

	return false
}

// SetAgentConnectionGroupId gets a reference to the given int32 and assigns it to the AgentConnectionGroupId field.
func (o *V1NetworkConnectionsServicesUpdateRequest) SetAgentConnectionGroupId(v int32) {
	o.AgentConnectionGroupId = &v
}

// GetChanges returns the Changes field value
func (o *V1NetworkConnectionsServicesUpdateRequest) GetChanges() []AgentServicesUpdateChanges {
	if o == nil {
		var ret []AgentServicesUpdateChanges
		return ret
	}

	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsServicesUpdateRequest) GetChangesOk() ([]AgentServicesUpdateChanges, bool) {
	if o == nil {
		return nil, false
	}
	return o.Changes, true
}

// SetChanges sets field value
func (o *V1NetworkConnectionsServicesUpdateRequest) SetChanges(v []AgentServicesUpdateChanges) {
	o.Changes = v
}

func (o V1NetworkConnectionsServicesUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentConnectionGroupId != nil {
		toSerialize["agent_connection_group_id"] = o.AgentConnectionGroupId
	}
	if true {
		toSerialize["changes"] = o.Changes
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkConnectionsServicesUpdateRequest struct {
	value *V1NetworkConnectionsServicesUpdateRequest
	isSet bool
}

func (v NullableV1NetworkConnectionsServicesUpdateRequest) Get() *V1NetworkConnectionsServicesUpdateRequest {
	return v.value
}

func (v *NullableV1NetworkConnectionsServicesUpdateRequest) Set(val *V1NetworkConnectionsServicesUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsServicesUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsServicesUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsServicesUpdateRequest(val *V1NetworkConnectionsServicesUpdateRequest) *NullableV1NetworkConnectionsServicesUpdateRequest {
	return &NullableV1NetworkConnectionsServicesUpdateRequest{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsServicesUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsServicesUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
