/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// V1NetworkConnectionsCreateP2PRequest struct for V1NetworkConnectionsCreateP2PRequest
type V1NetworkConnectionsCreateP2PRequest struct {
	AgentPairs []V1NetworkConnectionsCreateP2PRequestAgentPairs `json:"agent_pairs"`
	SdnEnabled *bool                                            `json:"sdn_enabled,omitempty"`
}

// NewV1NetworkConnectionsCreateP2PRequest instantiates a new V1NetworkConnectionsCreateP2PRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsCreateP2PRequest(agentPairs []V1NetworkConnectionsCreateP2PRequestAgentPairs) *V1NetworkConnectionsCreateP2PRequest {
	this := V1NetworkConnectionsCreateP2PRequest{}
	this.AgentPairs = agentPairs
	return &this
}

// NewV1NetworkConnectionsCreateP2PRequestWithDefaults instantiates a new V1NetworkConnectionsCreateP2PRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsCreateP2PRequestWithDefaults() *V1NetworkConnectionsCreateP2PRequest {
	this := V1NetworkConnectionsCreateP2PRequest{}
	return &this
}

// GetAgentPairs returns the AgentPairs field value
func (o *V1NetworkConnectionsCreateP2PRequest) GetAgentPairs() []V1NetworkConnectionsCreateP2PRequestAgentPairs {
	if o == nil {
		var ret []V1NetworkConnectionsCreateP2PRequestAgentPairs
		return ret
	}

	return o.AgentPairs
}

// GetAgentPairsOk returns a tuple with the AgentPairs field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateP2PRequest) GetAgentPairsOk() ([]V1NetworkConnectionsCreateP2PRequestAgentPairs, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentPairs, true
}

// SetAgentPairs sets field value
func (o *V1NetworkConnectionsCreateP2PRequest) SetAgentPairs(v []V1NetworkConnectionsCreateP2PRequestAgentPairs) {
	o.AgentPairs = v
}

// GetSdnEnabled returns the SdnEnabled field value if set, zero value otherwise.
func (o *V1NetworkConnectionsCreateP2PRequest) GetSdnEnabled() bool {
	if o == nil || o.SdnEnabled == nil {
		var ret bool
		return ret
	}
	return *o.SdnEnabled
}

// GetSdnEnabledOk returns a tuple with the SdnEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateP2PRequest) GetSdnEnabledOk() (*bool, bool) {
	if o == nil || o.SdnEnabled == nil {
		return nil, false
	}
	return o.SdnEnabled, true
}

// HasSdnEnabled returns a boolean if a field has been set.
func (o *V1NetworkConnectionsCreateP2PRequest) HasSdnEnabled() bool {
	if o != nil && o.SdnEnabled != nil {
		return true
	}

	return false
}

// SetSdnEnabled gets a reference to the given bool and assigns it to the SdnEnabled field.
func (o *V1NetworkConnectionsCreateP2PRequest) SetSdnEnabled(v bool) {
	o.SdnEnabled = &v
}

func (o V1NetworkConnectionsCreateP2PRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_pairs"] = o.AgentPairs
	}
	if o.SdnEnabled != nil {
		toSerialize["sdn_enabled"] = o.SdnEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkConnectionsCreateP2PRequest struct {
	value *V1NetworkConnectionsCreateP2PRequest
	isSet bool
}

func (v NullableV1NetworkConnectionsCreateP2PRequest) Get() *V1NetworkConnectionsCreateP2PRequest {
	return v.value
}

func (v *NullableV1NetworkConnectionsCreateP2PRequest) Set(val *V1NetworkConnectionsCreateP2PRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsCreateP2PRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsCreateP2PRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsCreateP2PRequest(val *V1NetworkConnectionsCreateP2PRequest) *NullableV1NetworkConnectionsCreateP2PRequest {
	return &NullableV1NetworkConnectionsCreateP2PRequest{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsCreateP2PRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsCreateP2PRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
