/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1ConnectionOrderInnerOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ConnectionOrderInnerOneOf{}

// V1ConnectionOrderInnerOneOf struct for V1ConnectionOrderInnerOneOf
type V1ConnectionOrderInnerOneOf struct {
	AgentConnectionGroupId Order `json:"agent_connection_group_id"`
}

// NewV1ConnectionOrderInnerOneOf instantiates a new V1ConnectionOrderInnerOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ConnectionOrderInnerOneOf(agentConnectionGroupId Order) *V1ConnectionOrderInnerOneOf {
	this := V1ConnectionOrderInnerOneOf{}
	this.AgentConnectionGroupId = agentConnectionGroupId
	return &this
}

// NewV1ConnectionOrderInnerOneOfWithDefaults instantiates a new V1ConnectionOrderInnerOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ConnectionOrderInnerOneOfWithDefaults() *V1ConnectionOrderInnerOneOf {
	this := V1ConnectionOrderInnerOneOf{}
	return &this
}

// GetAgentConnectionGroupId returns the AgentConnectionGroupId field value
func (o *V1ConnectionOrderInnerOneOf) GetAgentConnectionGroupId() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentConnectionGroupId
}

// GetAgentConnectionGroupIdOk returns a tuple with the AgentConnectionGroupId field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionOrderInnerOneOf) GetAgentConnectionGroupIdOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentConnectionGroupId, true
}

// SetAgentConnectionGroupId sets field value
func (o *V1ConnectionOrderInnerOneOf) SetAgentConnectionGroupId(v Order) {
	o.AgentConnectionGroupId = v
}

func (o V1ConnectionOrderInnerOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ConnectionOrderInnerOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_connection_group_id"] = o.AgentConnectionGroupId
	return toSerialize, nil
}

type NullableV1ConnectionOrderInnerOneOf struct {
	value *V1ConnectionOrderInnerOneOf
	isSet bool
}

func (v NullableV1ConnectionOrderInnerOneOf) Get() *V1ConnectionOrderInnerOneOf {
	return v.value
}

func (v *NullableV1ConnectionOrderInnerOneOf) Set(val *V1ConnectionOrderInnerOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ConnectionOrderInnerOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ConnectionOrderInnerOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ConnectionOrderInnerOneOf(val *V1ConnectionOrderInnerOneOf) *NullableV1ConnectionOrderInnerOneOf {
	return &NullableV1ConnectionOrderInnerOneOf{value: val, isSet: true}
}

func (v NullableV1ConnectionOrderInnerOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ConnectionOrderInnerOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
