/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1AgentOrderInnerAnyOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AgentOrderInnerAnyOf3{}

// V1AgentOrderInnerAnyOf3 struct for V1AgentOrderInnerAnyOf3
type V1AgentOrderInnerAnyOf3 struct {
	AgentLocationCountry Order `json:"agent_location_country"`
}

// NewV1AgentOrderInnerAnyOf3 instantiates a new V1AgentOrderInnerAnyOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AgentOrderInnerAnyOf3(agentLocationCountry Order) *V1AgentOrderInnerAnyOf3 {
	this := V1AgentOrderInnerAnyOf3{}
	this.AgentLocationCountry = agentLocationCountry
	return &this
}

// NewV1AgentOrderInnerAnyOf3WithDefaults instantiates a new V1AgentOrderInnerAnyOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AgentOrderInnerAnyOf3WithDefaults() *V1AgentOrderInnerAnyOf3 {
	this := V1AgentOrderInnerAnyOf3{}
	return &this
}

// GetAgentLocationCountry returns the AgentLocationCountry field value
func (o *V1AgentOrderInnerAnyOf3) GetAgentLocationCountry() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentLocationCountry
}

// GetAgentLocationCountryOk returns a tuple with the AgentLocationCountry field value
// and a boolean to check if the value has been set.
func (o *V1AgentOrderInnerAnyOf3) GetAgentLocationCountryOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentLocationCountry, true
}

// SetAgentLocationCountry sets field value
func (o *V1AgentOrderInnerAnyOf3) SetAgentLocationCountry(v Order) {
	o.AgentLocationCountry = v
}

func (o V1AgentOrderInnerAnyOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AgentOrderInnerAnyOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_location_country"] = o.AgentLocationCountry
	return toSerialize, nil
}

type NullableV1AgentOrderInnerAnyOf3 struct {
	value *V1AgentOrderInnerAnyOf3
	isSet bool
}

func (v NullableV1AgentOrderInnerAnyOf3) Get() *V1AgentOrderInnerAnyOf3 {
	return v.value
}

func (v *NullableV1AgentOrderInnerAnyOf3) Set(val *V1AgentOrderInnerAnyOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AgentOrderInnerAnyOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AgentOrderInnerAnyOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AgentOrderInnerAnyOf3(val *V1AgentOrderInnerAnyOf3) *NullableV1AgentOrderInnerAnyOf3 {
	return &NullableV1AgentOrderInnerAnyOf3{value: val, isSet: true}
}

func (v NullableV1AgentOrderInnerAnyOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AgentOrderInnerAnyOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
