/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkAuthAgentTokensGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkAuthAgentTokensGetResponse{}

// V1NetworkAuthAgentTokensGetResponse struct for V1NetworkAuthAgentTokensGetResponse
type V1NetworkAuthAgentTokensGetResponse struct {
	Data []V1AuthAgentToken `json:"data"`
}

// NewV1NetworkAuthAgentTokensGetResponse instantiates a new V1NetworkAuthAgentTokensGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAgentTokensGetResponse(data []V1AuthAgentToken) *V1NetworkAuthAgentTokensGetResponse {
	this := V1NetworkAuthAgentTokensGetResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAuthAgentTokensGetResponseWithDefaults instantiates a new V1NetworkAuthAgentTokensGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAgentTokensGetResponseWithDefaults() *V1NetworkAuthAgentTokensGetResponse {
	this := V1NetworkAuthAgentTokensGetResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAuthAgentTokensGetResponse) GetData() []V1AuthAgentToken {
	if o == nil {
		var ret []V1AuthAgentToken
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAgentTokensGetResponse) GetDataOk() ([]V1AuthAgentToken, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkAuthAgentTokensGetResponse) SetData(v []V1AuthAgentToken) {
	o.Data = v
}

func (o V1NetworkAuthAgentTokensGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkAuthAgentTokensGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkAuthAgentTokensGetResponse struct {
	value *V1NetworkAuthAgentTokensGetResponse
	isSet bool
}

func (v NullableV1NetworkAuthAgentTokensGetResponse) Get() *V1NetworkAuthAgentTokensGetResponse {
	return v.value
}

func (v *NullableV1NetworkAuthAgentTokensGetResponse) Set(val *V1NetworkAuthAgentTokensGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAgentTokensGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAgentTokensGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAgentTokensGetResponse(val *V1NetworkAuthAgentTokensGetResponse) *NullableV1NetworkAuthAgentTokensGetResponse {
	return &NullableV1NetworkAuthAgentTokensGetResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAgentTokensGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAgentTokensGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
