/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// ConnectionServiceAgentServiceSubnet struct for ConnectionServiceAgentServiceSubnet
type ConnectionServiceAgentServiceSubnet struct {
	AgentServiceSubnetIsActive bool   `json:"agent_service_subnet_is_active"`
	AgentServiceSubnetIp       string `json:"agent_service_subnet_ip"`
	AgentServiceSubnetId       int32  `json:"agent_service_subnet_id"`
}

// NewConnectionServiceAgentServiceSubnet instantiates a new ConnectionServiceAgentServiceSubnet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionServiceAgentServiceSubnet(agentServiceSubnetIsActive bool, agentServiceSubnetIp string, agentServiceSubnetId int32) *ConnectionServiceAgentServiceSubnet {
	this := ConnectionServiceAgentServiceSubnet{}
	this.AgentServiceSubnetIsActive = agentServiceSubnetIsActive
	this.AgentServiceSubnetIp = agentServiceSubnetIp
	this.AgentServiceSubnetId = agentServiceSubnetId
	return &this
}

// NewConnectionServiceAgentServiceSubnetWithDefaults instantiates a new ConnectionServiceAgentServiceSubnet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionServiceAgentServiceSubnetWithDefaults() *ConnectionServiceAgentServiceSubnet {
	this := ConnectionServiceAgentServiceSubnet{}
	return &this
}

// GetAgentServiceSubnetIsActive returns the AgentServiceSubnetIsActive field value
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AgentServiceSubnetIsActive
}

// GetAgentServiceSubnetIsActiveOk returns a tuple with the AgentServiceSubnetIsActive field value
// and a boolean to check if the value has been set.
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServiceSubnetIsActive, true
}

// SetAgentServiceSubnetIsActive sets field value
func (o *ConnectionServiceAgentServiceSubnet) SetAgentServiceSubnetIsActive(v bool) {
	o.AgentServiceSubnetIsActive = v
}

// GetAgentServiceSubnetIp returns the AgentServiceSubnetIp field value
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentServiceSubnetIp
}

// GetAgentServiceSubnetIpOk returns a tuple with the AgentServiceSubnetIp field value
// and a boolean to check if the value has been set.
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServiceSubnetIp, true
}

// SetAgentServiceSubnetIp sets field value
func (o *ConnectionServiceAgentServiceSubnet) SetAgentServiceSubnetIp(v string) {
	o.AgentServiceSubnetIp = v
}

// GetAgentServiceSubnetId returns the AgentServiceSubnetId field value
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentServiceSubnetId
}

// GetAgentServiceSubnetIdOk returns a tuple with the AgentServiceSubnetId field value
// and a boolean to check if the value has been set.
func (o *ConnectionServiceAgentServiceSubnet) GetAgentServiceSubnetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentServiceSubnetId, true
}

// SetAgentServiceSubnetId sets field value
func (o *ConnectionServiceAgentServiceSubnet) SetAgentServiceSubnetId(v int32) {
	o.AgentServiceSubnetId = v
}

func (o ConnectionServiceAgentServiceSubnet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_service_subnet_is_active"] = o.AgentServiceSubnetIsActive
	}
	if true {
		toSerialize["agent_service_subnet_ip"] = o.AgentServiceSubnetIp
	}
	if true {
		toSerialize["agent_service_subnet_id"] = o.AgentServiceSubnetId
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionServiceAgentServiceSubnet struct {
	value *ConnectionServiceAgentServiceSubnet
	isSet bool
}

func (v NullableConnectionServiceAgentServiceSubnet) Get() *ConnectionServiceAgentServiceSubnet {
	return v.value
}

func (v *NullableConnectionServiceAgentServiceSubnet) Set(val *ConnectionServiceAgentServiceSubnet) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionServiceAgentServiceSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionServiceAgentServiceSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionServiceAgentServiceSubnet(val *ConnectionServiceAgentServiceSubnet) *NullableConnectionServiceAgentServiceSubnet {
	return &NullableConnectionServiceAgentServiceSubnet{value: val, isSet: true}
}

func (v NullableConnectionServiceAgentServiceSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionServiceAgentServiceSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
