/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1AgentOrderInnerAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AgentOrderInnerAnyOf1{}

// V1AgentOrderInnerAnyOf1 struct for V1AgentOrderInnerAnyOf1
type V1AgentOrderInnerAnyOf1 struct {
	AgentProviderName Order `json:"agent_provider_name"`
}

// NewV1AgentOrderInnerAnyOf1 instantiates a new V1AgentOrderInnerAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AgentOrderInnerAnyOf1(agentProviderName Order) *V1AgentOrderInnerAnyOf1 {
	this := V1AgentOrderInnerAnyOf1{}
	this.AgentProviderName = agentProviderName
	return &this
}

// NewV1AgentOrderInnerAnyOf1WithDefaults instantiates a new V1AgentOrderInnerAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AgentOrderInnerAnyOf1WithDefaults() *V1AgentOrderInnerAnyOf1 {
	this := V1AgentOrderInnerAnyOf1{}
	return &this
}

// GetAgentProviderName returns the AgentProviderName field value
func (o *V1AgentOrderInnerAnyOf1) GetAgentProviderName() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentProviderName
}

// GetAgentProviderNameOk returns a tuple with the AgentProviderName field value
// and a boolean to check if the value has been set.
func (o *V1AgentOrderInnerAnyOf1) GetAgentProviderNameOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentProviderName, true
}

// SetAgentProviderName sets field value
func (o *V1AgentOrderInnerAnyOf1) SetAgentProviderName(v Order) {
	o.AgentProviderName = v
}

func (o V1AgentOrderInnerAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AgentOrderInnerAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_provider_name"] = o.AgentProviderName
	return toSerialize, nil
}

type NullableV1AgentOrderInnerAnyOf1 struct {
	value *V1AgentOrderInnerAnyOf1
	isSet bool
}

func (v NullableV1AgentOrderInnerAnyOf1) Get() *V1AgentOrderInnerAnyOf1 {
	return v.value
}

func (v *NullableV1AgentOrderInnerAnyOf1) Set(val *V1AgentOrderInnerAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AgentOrderInnerAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AgentOrderInnerAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AgentOrderInnerAnyOf1(val *V1AgentOrderInnerAnyOf1) *NullableV1AgentOrderInnerAnyOf1 {
	return &NullableV1AgentOrderInnerAnyOf1{value: val, isSet: true}
}

func (v NullableV1AgentOrderInnerAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AgentOrderInnerAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
