/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the AgentTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentTag{}

// AgentTag struct for AgentTag
type AgentTag struct {
	AgentTagName string `json:"agent_tag_name"`
	AgentTagId   int32  `json:"agent_tag_id"`
}

// NewAgentTag instantiates a new AgentTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentTag(agentTagName string, agentTagId int32) *AgentTag {
	this := AgentTag{}
	this.AgentTagName = agentTagName
	this.AgentTagId = agentTagId
	return &this
}

// NewAgentTagWithDefaults instantiates a new AgentTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentTagWithDefaults() *AgentTag {
	this := AgentTag{}
	return &this
}

// GetAgentTagName returns the AgentTagName field value
func (o *AgentTag) GetAgentTagName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentTagName
}

// GetAgentTagNameOk returns a tuple with the AgentTagName field value
// and a boolean to check if the value has been set.
func (o *AgentTag) GetAgentTagNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentTagName, true
}

// SetAgentTagName sets field value
func (o *AgentTag) SetAgentTagName(v string) {
	o.AgentTagName = v
}

// GetAgentTagId returns the AgentTagId field value
func (o *AgentTag) GetAgentTagId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentTagId
}

// GetAgentTagIdOk returns a tuple with the AgentTagId field value
// and a boolean to check if the value has been set.
func (o *AgentTag) GetAgentTagIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentTagId, true
}

// SetAgentTagId sets field value
func (o *AgentTag) SetAgentTagId(v int32) {
	o.AgentTagId = v
}

func (o AgentTag) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_tag_name"] = o.AgentTagName
	toSerialize["agent_tag_id"] = o.AgentTagId
	return toSerialize, nil
}

type NullableAgentTag struct {
	value *AgentTag
	isSet bool
}

func (v NullableAgentTag) Get() *AgentTag {
	return v.value
}

func (v *NullableAgentTag) Set(val *AgentTag) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentTag) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentTag(val *AgentTag) *NullableAgentTag {
	return &NullableAgentTag{value: val, isSet: true}
}

func (v NullableAgentTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
