/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1NetworkAgentsGetResponse struct for V1NetworkAgentsGetResponse
type V1NetworkAgentsGetResponse struct {
	Data []V1Agent `json:"data"`
}

// NewV1NetworkAgentsGetResponse instantiates a new V1NetworkAgentsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAgentsGetResponse(data []V1Agent) *V1NetworkAgentsGetResponse {
	this := V1NetworkAgentsGetResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAgentsGetResponseWithDefaults instantiates a new V1NetworkAgentsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAgentsGetResponseWithDefaults() *V1NetworkAgentsGetResponse {
	this := V1NetworkAgentsGetResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAgentsGetResponse) GetData() []V1Agent {
	if o == nil {
		var ret []V1Agent
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsGetResponse) GetDataOk() ([]V1Agent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkAgentsGetResponse) SetData(v []V1Agent) {
	o.Data = v
}

func (o V1NetworkAgentsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAgentsGetResponse struct {
	value *V1NetworkAgentsGetResponse
	isSet bool
}

func (v NullableV1NetworkAgentsGetResponse) Get() *V1NetworkAgentsGetResponse {
	return v.value
}

func (v *NullableV1NetworkAgentsGetResponse) Set(val *V1NetworkAgentsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAgentsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAgentsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAgentsGetResponse(val *V1NetworkAgentsGetResponse) *NullableV1NetworkAgentsGetResponse {
	return &NullableV1NetworkAgentsGetResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAgentsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAgentsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
