/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1ErrorResponseErrors struct for V1ErrorResponseErrors
type V1ErrorResponseErrors struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// NewV1ErrorResponseErrors instantiates a new V1ErrorResponseErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ErrorResponseErrors() *V1ErrorResponseErrors {
	this := V1ErrorResponseErrors{}
	return &this
}

// NewV1ErrorResponseErrorsWithDefaults instantiates a new V1ErrorResponseErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ErrorResponseErrorsWithDefaults() *V1ErrorResponseErrors {
	this := V1ErrorResponseErrors{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *V1ErrorResponseErrors) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ErrorResponseErrors) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *V1ErrorResponseErrors) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *V1ErrorResponseErrors) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V1ErrorResponseErrors) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ErrorResponseErrors) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V1ErrorResponseErrors) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V1ErrorResponseErrors) SetMessage(v string) {
	o.Message = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V1ErrorResponseErrors) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ErrorResponseErrors) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V1ErrorResponseErrors) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V1ErrorResponseErrors) SetType(v string) {
	o.Type = &v
}

func (o V1ErrorResponseErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableV1ErrorResponseErrors struct {
	value *V1ErrorResponseErrors
	isSet bool
}

func (v NullableV1ErrorResponseErrors) Get() *V1ErrorResponseErrors {
	return v.value
}

func (v *NullableV1ErrorResponseErrors) Set(val *V1ErrorResponseErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ErrorResponseErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ErrorResponseErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ErrorResponseErrors(val *V1ErrorResponseErrors) *NullableV1ErrorResponseErrors {
	return &NullableV1ErrorResponseErrors{value: val, isSet: true}
}

func (v NullableV1ErrorResponseErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ErrorResponseErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
