/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
	"time"
)

// V1NetworkAuthAgentTokensCreateRequest struct for V1NetworkAuthAgentTokensCreateRequest
type V1NetworkAuthAgentTokensCreateRequest struct {
	AgentTokenName            string     `json:"agent_token_name"`
	AgentTokenDescription     *string    `json:"agent_token_description,omitempty"`
	AgentTokenValidUntil      *time.Time `json:"agent_token_valid_until,omitempty"`
	AgentTokenAllowedTagNames []string   `json:"agent_token_allowed_tag_names,omitempty"`
}

// NewV1NetworkAuthAgentTokensCreateRequest instantiates a new V1NetworkAuthAgentTokensCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAgentTokensCreateRequest(agentTokenName string) *V1NetworkAuthAgentTokensCreateRequest {
	this := V1NetworkAuthAgentTokensCreateRequest{}
	this.AgentTokenName = agentTokenName
	return &this
}

// NewV1NetworkAuthAgentTokensCreateRequestWithDefaults instantiates a new V1NetworkAuthAgentTokensCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAgentTokensCreateRequestWithDefaults() *V1NetworkAuthAgentTokensCreateRequest {
	this := V1NetworkAuthAgentTokensCreateRequest{}
	return &this
}

// GetAgentTokenName returns the AgentTokenName field value
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentTokenName
}

// GetAgentTokenNameOk returns a tuple with the AgentTokenName field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentTokenName, true
}

// SetAgentTokenName sets field value
func (o *V1NetworkAuthAgentTokensCreateRequest) SetAgentTokenName(v string) {
	o.AgentTokenName = v
}

// GetAgentTokenDescription returns the AgentTokenDescription field value if set, zero value otherwise.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenDescription() string {
	if o == nil || o.AgentTokenDescription == nil {
		var ret string
		return ret
	}
	return *o.AgentTokenDescription
}

// GetAgentTokenDescriptionOk returns a tuple with the AgentTokenDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenDescriptionOk() (*string, bool) {
	if o == nil || o.AgentTokenDescription == nil {
		return nil, false
	}
	return o.AgentTokenDescription, true
}

// HasAgentTokenDescription returns a boolean if a field has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) HasAgentTokenDescription() bool {
	if o != nil && o.AgentTokenDescription != nil {
		return true
	}

	return false
}

// SetAgentTokenDescription gets a reference to the given string and assigns it to the AgentTokenDescription field.
func (o *V1NetworkAuthAgentTokensCreateRequest) SetAgentTokenDescription(v string) {
	o.AgentTokenDescription = &v
}

// GetAgentTokenValidUntil returns the AgentTokenValidUntil field value if set, zero value otherwise.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenValidUntil() time.Time {
	if o == nil || o.AgentTokenValidUntil == nil {
		var ret time.Time
		return ret
	}
	return *o.AgentTokenValidUntil
}

// GetAgentTokenValidUntilOk returns a tuple with the AgentTokenValidUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenValidUntilOk() (*time.Time, bool) {
	if o == nil || o.AgentTokenValidUntil == nil {
		return nil, false
	}
	return o.AgentTokenValidUntil, true
}

// HasAgentTokenValidUntil returns a boolean if a field has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) HasAgentTokenValidUntil() bool {
	if o != nil && o.AgentTokenValidUntil != nil {
		return true
	}

	return false
}

// SetAgentTokenValidUntil gets a reference to the given time.Time and assigns it to the AgentTokenValidUntil field.
func (o *V1NetworkAuthAgentTokensCreateRequest) SetAgentTokenValidUntil(v time.Time) {
	o.AgentTokenValidUntil = &v
}

// GetAgentTokenAllowedTagNames returns the AgentTokenAllowedTagNames field value if set, zero value otherwise.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenAllowedTagNames() []string {
	if o == nil || o.AgentTokenAllowedTagNames == nil {
		var ret []string
		return ret
	}
	return o.AgentTokenAllowedTagNames
}

// GetAgentTokenAllowedTagNamesOk returns a tuple with the AgentTokenAllowedTagNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) GetAgentTokenAllowedTagNamesOk() ([]string, bool) {
	if o == nil || o.AgentTokenAllowedTagNames == nil {
		return nil, false
	}
	return o.AgentTokenAllowedTagNames, true
}

// HasAgentTokenAllowedTagNames returns a boolean if a field has been set.
func (o *V1NetworkAuthAgentTokensCreateRequest) HasAgentTokenAllowedTagNames() bool {
	if o != nil && o.AgentTokenAllowedTagNames != nil {
		return true
	}

	return false
}

// SetAgentTokenAllowedTagNames gets a reference to the given []string and assigns it to the AgentTokenAllowedTagNames field.
func (o *V1NetworkAuthAgentTokensCreateRequest) SetAgentTokenAllowedTagNames(v []string) {
	o.AgentTokenAllowedTagNames = v
}

func (o V1NetworkAuthAgentTokensCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_token_name"] = o.AgentTokenName
	}
	if o.AgentTokenDescription != nil {
		toSerialize["agent_token_description"] = o.AgentTokenDescription
	}
	if o.AgentTokenValidUntil != nil {
		toSerialize["agent_token_valid_until"] = o.AgentTokenValidUntil
	}
	if o.AgentTokenAllowedTagNames != nil {
		toSerialize["agent_token_allowed_tag_names"] = o.AgentTokenAllowedTagNames
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAuthAgentTokensCreateRequest struct {
	value *V1NetworkAuthAgentTokensCreateRequest
	isSet bool
}

func (v NullableV1NetworkAuthAgentTokensCreateRequest) Get() *V1NetworkAuthAgentTokensCreateRequest {
	return v.value
}

func (v *NullableV1NetworkAuthAgentTokensCreateRequest) Set(val *V1NetworkAuthAgentTokensCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAgentTokensCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAgentTokensCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAgentTokensCreateRequest(val *V1NetworkAuthAgentTokensCreateRequest) *NullableV1NetworkAuthAgentTokensCreateRequest {
	return &NullableV1NetworkAuthAgentTokensCreateRequest{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAgentTokensCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAgentTokensCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
