/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkAuthAccessTokensPermissionsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkAuthAccessTokensPermissionsGetResponse{}

// V1NetworkAuthAccessTokensPermissionsGetResponse struct for V1NetworkAuthAccessTokensPermissionsGetResponse
type V1NetworkAuthAccessTokensPermissionsGetResponse struct {
	Data []V1AuthAccessTokenPermissions `json:"data"`
}

// NewV1NetworkAuthAccessTokensPermissionsGetResponse instantiates a new V1NetworkAuthAccessTokensPermissionsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAccessTokensPermissionsGetResponse(data []V1AuthAccessTokenPermissions) *V1NetworkAuthAccessTokensPermissionsGetResponse {
	this := V1NetworkAuthAccessTokensPermissionsGetResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAuthAccessTokensPermissionsGetResponseWithDefaults instantiates a new V1NetworkAuthAccessTokensPermissionsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAccessTokensPermissionsGetResponseWithDefaults() *V1NetworkAuthAccessTokensPermissionsGetResponse {
	this := V1NetworkAuthAccessTokensPermissionsGetResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAuthAccessTokensPermissionsGetResponse) GetData() []V1AuthAccessTokenPermissions {
	if o == nil {
		var ret []V1AuthAccessTokenPermissions
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensPermissionsGetResponse) GetDataOk() ([]V1AuthAccessTokenPermissions, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkAuthAccessTokensPermissionsGetResponse) SetData(v []V1AuthAccessTokenPermissions) {
	o.Data = v
}

func (o V1NetworkAuthAccessTokensPermissionsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkAuthAccessTokensPermissionsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkAuthAccessTokensPermissionsGetResponse struct {
	value *V1NetworkAuthAccessTokensPermissionsGetResponse
	isSet bool
}

func (v NullableV1NetworkAuthAccessTokensPermissionsGetResponse) Get() *V1NetworkAuthAccessTokensPermissionsGetResponse {
	return v.value
}

func (v *NullableV1NetworkAuthAccessTokensPermissionsGetResponse) Set(val *V1NetworkAuthAccessTokensPermissionsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAccessTokensPermissionsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAccessTokensPermissionsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAccessTokensPermissionsGetResponse(val *V1NetworkAuthAccessTokensPermissionsGetResponse) *NullableV1NetworkAuthAccessTokensPermissionsGetResponse {
	return &NullableV1NetworkAuthAccessTokensPermissionsGetResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAccessTokensPermissionsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAccessTokensPermissionsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
