/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1ConnectionOrderInnerOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ConnectionOrderInnerOneOf3{}

// V1ConnectionOrderInnerOneOf3 struct for V1ConnectionOrderInnerOneOf3
type V1ConnectionOrderInnerOneOf3 struct {
	AgentConnectionGroupUpdatedAt Order `json:"agent_connection_group_updated_at"`
}

// NewV1ConnectionOrderInnerOneOf3 instantiates a new V1ConnectionOrderInnerOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ConnectionOrderInnerOneOf3(agentConnectionGroupUpdatedAt Order) *V1ConnectionOrderInnerOneOf3 {
	this := V1ConnectionOrderInnerOneOf3{}
	this.AgentConnectionGroupUpdatedAt = agentConnectionGroupUpdatedAt
	return &this
}

// NewV1ConnectionOrderInnerOneOf3WithDefaults instantiates a new V1ConnectionOrderInnerOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ConnectionOrderInnerOneOf3WithDefaults() *V1ConnectionOrderInnerOneOf3 {
	this := V1ConnectionOrderInnerOneOf3{}
	return &this
}

// GetAgentConnectionGroupUpdatedAt returns the AgentConnectionGroupUpdatedAt field value
func (o *V1ConnectionOrderInnerOneOf3) GetAgentConnectionGroupUpdatedAt() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.AgentConnectionGroupUpdatedAt
}

// GetAgentConnectionGroupUpdatedAtOk returns a tuple with the AgentConnectionGroupUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *V1ConnectionOrderInnerOneOf3) GetAgentConnectionGroupUpdatedAtOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentConnectionGroupUpdatedAt, true
}

// SetAgentConnectionGroupUpdatedAt sets field value
func (o *V1ConnectionOrderInnerOneOf3) SetAgentConnectionGroupUpdatedAt(v Order) {
	o.AgentConnectionGroupUpdatedAt = v
}

func (o V1ConnectionOrderInnerOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ConnectionOrderInnerOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_connection_group_updated_at"] = o.AgentConnectionGroupUpdatedAt
	return toSerialize, nil
}

type NullableV1ConnectionOrderInnerOneOf3 struct {
	value *V1ConnectionOrderInnerOneOf3
	isSet bool
}

func (v NullableV1ConnectionOrderInnerOneOf3) Get() *V1ConnectionOrderInnerOneOf3 {
	return v.value
}

func (v *NullableV1ConnectionOrderInnerOneOf3) Set(val *V1ConnectionOrderInnerOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ConnectionOrderInnerOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ConnectionOrderInnerOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ConnectionOrderInnerOneOf3(val *V1ConnectionOrderInnerOneOf3) *NullableV1ConnectionOrderInnerOneOf3 {
	return &NullableV1ConnectionOrderInnerOneOf3{value: val, isSet: true}
}

func (v NullableV1ConnectionOrderInnerOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ConnectionOrderInnerOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
