/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1NetworkAgentsCreateResponse struct for V1NetworkAgentsCreateResponse
type V1NetworkAgentsCreateResponse struct {
	Data V1AgentCreateItem `json:"data"`
}

// NewV1NetworkAgentsCreateResponse instantiates a new V1NetworkAgentsCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAgentsCreateResponse(data V1AgentCreateItem) *V1NetworkAgentsCreateResponse {
	this := V1NetworkAgentsCreateResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkAgentsCreateResponseWithDefaults instantiates a new V1NetworkAgentsCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAgentsCreateResponseWithDefaults() *V1NetworkAgentsCreateResponse {
	this := V1NetworkAgentsCreateResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkAgentsCreateResponse) GetData() V1AgentCreateItem {
	if o == nil {
		var ret V1AgentCreateItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAgentsCreateResponse) GetDataOk() (*V1AgentCreateItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *V1NetworkAgentsCreateResponse) SetData(v V1AgentCreateItem) {
	o.Data = v
}

func (o V1NetworkAgentsCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAgentsCreateResponse struct {
	value *V1NetworkAgentsCreateResponse
	isSet bool
}

func (v NullableV1NetworkAgentsCreateResponse) Get() *V1NetworkAgentsCreateResponse {
	return v.value
}

func (v *NullableV1NetworkAgentsCreateResponse) Set(val *V1NetworkAgentsCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAgentsCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAgentsCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAgentsCreateResponse(val *V1NetworkAgentsCreateResponse) *NullableV1NetworkAgentsCreateResponse {
	return &NullableV1NetworkAgentsCreateResponse{value: val, isSet: true}
}

func (v NullableV1NetworkAgentsCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAgentsCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
