/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1AuthAccessTokenPermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthAccessTokenPermissions{}

// V1AuthAccessTokenPermissions struct for V1AuthAccessTokenPermissions
type V1AuthAccessTokenPermissions struct {
	PermissionId          int32  `json:"permission_id"`
	PermissionName        string `json:"permission_name"`
	PermissionDescription string `json:"permission_description"`
}

// NewV1AuthAccessTokenPermissions instantiates a new V1AuthAccessTokenPermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthAccessTokenPermissions(permissionId int32, permissionName string, permissionDescription string) *V1AuthAccessTokenPermissions {
	this := V1AuthAccessTokenPermissions{}
	this.PermissionId = permissionId
	this.PermissionName = permissionName
	this.PermissionDescription = permissionDescription
	return &this
}

// NewV1AuthAccessTokenPermissionsWithDefaults instantiates a new V1AuthAccessTokenPermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthAccessTokenPermissionsWithDefaults() *V1AuthAccessTokenPermissions {
	this := V1AuthAccessTokenPermissions{}
	return &this
}

// GetPermissionId returns the PermissionId field value
func (o *V1AuthAccessTokenPermissions) GetPermissionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PermissionId
}

// GetPermissionIdOk returns a tuple with the PermissionId field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessTokenPermissions) GetPermissionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionId, true
}

// SetPermissionId sets field value
func (o *V1AuthAccessTokenPermissions) SetPermissionId(v int32) {
	o.PermissionId = v
}

// GetPermissionName returns the PermissionName field value
func (o *V1AuthAccessTokenPermissions) GetPermissionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PermissionName
}

// GetPermissionNameOk returns a tuple with the PermissionName field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessTokenPermissions) GetPermissionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionName, true
}

// SetPermissionName sets field value
func (o *V1AuthAccessTokenPermissions) SetPermissionName(v string) {
	o.PermissionName = v
}

// GetPermissionDescription returns the PermissionDescription field value
func (o *V1AuthAccessTokenPermissions) GetPermissionDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PermissionDescription
}

// GetPermissionDescriptionOk returns a tuple with the PermissionDescription field value
// and a boolean to check if the value has been set.
func (o *V1AuthAccessTokenPermissions) GetPermissionDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionDescription, true
}

// SetPermissionDescription sets field value
func (o *V1AuthAccessTokenPermissions) SetPermissionDescription(v string) {
	o.PermissionDescription = v
}

func (o V1AuthAccessTokenPermissions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthAccessTokenPermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permission_id"] = o.PermissionId
	toSerialize["permission_name"] = o.PermissionName
	toSerialize["permission_description"] = o.PermissionDescription
	return toSerialize, nil
}

type NullableV1AuthAccessTokenPermissions struct {
	value *V1AuthAccessTokenPermissions
	isSet bool
}

func (v NullableV1AuthAccessTokenPermissions) Get() *V1AuthAccessTokenPermissions {
	return v.value
}

func (v *NullableV1AuthAccessTokenPermissions) Set(val *V1AuthAccessTokenPermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthAccessTokenPermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthAccessTokenPermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthAccessTokenPermissions(val *V1AuthAccessTokenPermissions) *NullableV1AuthAccessTokenPermissions {
	return &NullableV1AuthAccessTokenPermissions{value: val, isSet: true}
}

func (v NullableV1AuthAccessTokenPermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthAccessTokenPermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
