/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkConnectionsSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkConnectionsSearchResponse{}

// V1NetworkConnectionsSearchResponse struct for V1NetworkConnectionsSearchResponse
type V1NetworkConnectionsSearchResponse struct {
	Data []V1Connection `json:"data"`
}

// NewV1NetworkConnectionsSearchResponse instantiates a new V1NetworkConnectionsSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsSearchResponse(data []V1Connection) *V1NetworkConnectionsSearchResponse {
	this := V1NetworkConnectionsSearchResponse{}
	this.Data = data
	return &this
}

// NewV1NetworkConnectionsSearchResponseWithDefaults instantiates a new V1NetworkConnectionsSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsSearchResponseWithDefaults() *V1NetworkConnectionsSearchResponse {
	this := V1NetworkConnectionsSearchResponse{}
	return &this
}

// GetData returns the Data field value
func (o *V1NetworkConnectionsSearchResponse) GetData() []V1Connection {
	if o == nil {
		var ret []V1Connection
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsSearchResponse) GetDataOk() ([]V1Connection, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *V1NetworkConnectionsSearchResponse) SetData(v []V1Connection) {
	o.Data = v
}

func (o V1NetworkConnectionsSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkConnectionsSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableV1NetworkConnectionsSearchResponse struct {
	value *V1NetworkConnectionsSearchResponse
	isSet bool
}

func (v NullableV1NetworkConnectionsSearchResponse) Get() *V1NetworkConnectionsSearchResponse {
	return v.value
}

func (v *NullableV1NetworkConnectionsSearchResponse) Set(val *V1NetworkConnectionsSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsSearchResponse(val *V1NetworkConnectionsSearchResponse) *NullableV1NetworkConnectionsSearchResponse {
	return &NullableV1NetworkConnectionsSearchResponse{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
