/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// V1NetworkConnectionsCreateMeshRequest struct for V1NetworkConnectionsCreateMeshRequest
type V1NetworkConnectionsCreateMeshRequest struct {
	AgentIds   []V1NetworkConnectionsCreateMeshRequestAgentIds `json:"agent_ids"`
	SdnEnabled *bool                                           `json:"sdn_enabled,omitempty"`
}

// NewV1NetworkConnectionsCreateMeshRequest instantiates a new V1NetworkConnectionsCreateMeshRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsCreateMeshRequest(agentIds []V1NetworkConnectionsCreateMeshRequestAgentIds) *V1NetworkConnectionsCreateMeshRequest {
	this := V1NetworkConnectionsCreateMeshRequest{}
	this.AgentIds = agentIds
	return &this
}

// NewV1NetworkConnectionsCreateMeshRequestWithDefaults instantiates a new V1NetworkConnectionsCreateMeshRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsCreateMeshRequestWithDefaults() *V1NetworkConnectionsCreateMeshRequest {
	this := V1NetworkConnectionsCreateMeshRequest{}
	return &this
}

// GetAgentIds returns the AgentIds field value
func (o *V1NetworkConnectionsCreateMeshRequest) GetAgentIds() []V1NetworkConnectionsCreateMeshRequestAgentIds {
	if o == nil {
		var ret []V1NetworkConnectionsCreateMeshRequestAgentIds
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateMeshRequest) GetAgentIdsOk() ([]V1NetworkConnectionsCreateMeshRequestAgentIds, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *V1NetworkConnectionsCreateMeshRequest) SetAgentIds(v []V1NetworkConnectionsCreateMeshRequestAgentIds) {
	o.AgentIds = v
}

// GetSdnEnabled returns the SdnEnabled field value if set, zero value otherwise.
func (o *V1NetworkConnectionsCreateMeshRequest) GetSdnEnabled() bool {
	if o == nil || o.SdnEnabled == nil {
		var ret bool
		return ret
	}
	return *o.SdnEnabled
}

// GetSdnEnabledOk returns a tuple with the SdnEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateMeshRequest) GetSdnEnabledOk() (*bool, bool) {
	if o == nil || o.SdnEnabled == nil {
		return nil, false
	}
	return o.SdnEnabled, true
}

// HasSdnEnabled returns a boolean if a field has been set.
func (o *V1NetworkConnectionsCreateMeshRequest) HasSdnEnabled() bool {
	if o != nil && o.SdnEnabled != nil {
		return true
	}

	return false
}

// SetSdnEnabled gets a reference to the given bool and assigns it to the SdnEnabled field.
func (o *V1NetworkConnectionsCreateMeshRequest) SetSdnEnabled(v bool) {
	o.SdnEnabled = &v
}

func (o V1NetworkConnectionsCreateMeshRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["agent_ids"] = o.AgentIds
	}
	if o.SdnEnabled != nil {
		toSerialize["sdn_enabled"] = o.SdnEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkConnectionsCreateMeshRequest struct {
	value *V1NetworkConnectionsCreateMeshRequest
	isSet bool
}

func (v NullableV1NetworkConnectionsCreateMeshRequest) Get() *V1NetworkConnectionsCreateMeshRequest {
	return v.value
}

func (v *NullableV1NetworkConnectionsCreateMeshRequest) Set(val *V1NetworkConnectionsCreateMeshRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsCreateMeshRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsCreateMeshRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsCreateMeshRequest(val *V1NetworkConnectionsCreateMeshRequest) *NullableV1NetworkConnectionsCreateMeshRequest {
	return &NullableV1NetworkConnectionsCreateMeshRequest{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsCreateMeshRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsCreateMeshRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
