/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package syntropy

import (
	"encoding/json"
)

// checks if the V1NetworkConnectionsCreateMeshRequestAgentIdsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NetworkConnectionsCreateMeshRequestAgentIdsInner{}

// V1NetworkConnectionsCreateMeshRequestAgentIdsInner struct for V1NetworkConnectionsCreateMeshRequestAgentIdsInner
type V1NetworkConnectionsCreateMeshRequestAgentIdsInner struct {
	AgentId int32 `json:"agent_id"`
}

// NewV1NetworkConnectionsCreateMeshRequestAgentIdsInner instantiates a new V1NetworkConnectionsCreateMeshRequestAgentIdsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkConnectionsCreateMeshRequestAgentIdsInner(agentId int32) *V1NetworkConnectionsCreateMeshRequestAgentIdsInner {
	this := V1NetworkConnectionsCreateMeshRequestAgentIdsInner{}
	this.AgentId = agentId
	return &this
}

// NewV1NetworkConnectionsCreateMeshRequestAgentIdsInnerWithDefaults instantiates a new V1NetworkConnectionsCreateMeshRequestAgentIdsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkConnectionsCreateMeshRequestAgentIdsInnerWithDefaults() *V1NetworkConnectionsCreateMeshRequestAgentIdsInner {
	this := V1NetworkConnectionsCreateMeshRequestAgentIdsInner{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *V1NetworkConnectionsCreateMeshRequestAgentIdsInner) GetAgentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *V1NetworkConnectionsCreateMeshRequestAgentIdsInner) GetAgentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *V1NetworkConnectionsCreateMeshRequestAgentIdsInner) SetAgentId(v int32) {
	o.AgentId = v
}

func (o V1NetworkConnectionsCreateMeshRequestAgentIdsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NetworkConnectionsCreateMeshRequestAgentIdsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	return toSerialize, nil
}

type NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner struct {
	value *V1NetworkConnectionsCreateMeshRequestAgentIdsInner
	isSet bool
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) Get() *V1NetworkConnectionsCreateMeshRequestAgentIdsInner {
	return v.value
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) Set(val *V1NetworkConnectionsCreateMeshRequestAgentIdsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner(val *V1NetworkConnectionsCreateMeshRequestAgentIdsInner) *NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner {
	return &NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner{value: val, isSet: true}
}

func (v NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkConnectionsCreateMeshRequestAgentIdsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
