/*
Syntropy network API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: support@syntropynet.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// V1NetworkAuthAccessTokensCreateRequest struct for V1NetworkAuthAccessTokensCreateRequest
type V1NetworkAuthAccessTokensCreateRequest struct {
	Permissions            []string  `json:"permissions"`
	AccessTokenExpiration  time.Time `json:"access_token_expiration"`
	AccessTokenName        string    `json:"access_token_name"`
	AccessTokenDescription *string   `json:"access_token_description,omitempty"`
}

// NewV1NetworkAuthAccessTokensCreateRequest instantiates a new V1NetworkAuthAccessTokensCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NetworkAuthAccessTokensCreateRequest(permissions []string, accessTokenExpiration time.Time, accessTokenName string) *V1NetworkAuthAccessTokensCreateRequest {
	this := V1NetworkAuthAccessTokensCreateRequest{}
	this.Permissions = permissions
	this.AccessTokenExpiration = accessTokenExpiration
	this.AccessTokenName = accessTokenName
	return &this
}

// NewV1NetworkAuthAccessTokensCreateRequestWithDefaults instantiates a new V1NetworkAuthAccessTokensCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NetworkAuthAccessTokensCreateRequestWithDefaults() *V1NetworkAuthAccessTokensCreateRequest {
	this := V1NetworkAuthAccessTokensCreateRequest{}
	return &this
}

// GetPermissions returns the Permissions field value
func (o *V1NetworkAuthAccessTokensCreateRequest) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensCreateRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Permissions, true
}

// SetPermissions sets field value
func (o *V1NetworkAuthAccessTokensCreateRequest) SetPermissions(v []string) {
	o.Permissions = v
}

// GetAccessTokenExpiration returns the AccessTokenExpiration field value
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenExpiration() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AccessTokenExpiration
}

// GetAccessTokenExpirationOk returns a tuple with the AccessTokenExpiration field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenExpirationOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenExpiration, true
}

// SetAccessTokenExpiration sets field value
func (o *V1NetworkAuthAccessTokensCreateRequest) SetAccessTokenExpiration(v time.Time) {
	o.AccessTokenExpiration = v
}

// GetAccessTokenName returns the AccessTokenName field value
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessTokenName
}

// GetAccessTokenNameOk returns a tuple with the AccessTokenName field value
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenName, true
}

// SetAccessTokenName sets field value
func (o *V1NetworkAuthAccessTokensCreateRequest) SetAccessTokenName(v string) {
	o.AccessTokenName = v
}

// GetAccessTokenDescription returns the AccessTokenDescription field value if set, zero value otherwise.
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenDescription() string {
	if o == nil || o.AccessTokenDescription == nil {
		var ret string
		return ret
	}
	return *o.AccessTokenDescription
}

// GetAccessTokenDescriptionOk returns a tuple with the AccessTokenDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1NetworkAuthAccessTokensCreateRequest) GetAccessTokenDescriptionOk() (*string, bool) {
	if o == nil || o.AccessTokenDescription == nil {
		return nil, false
	}
	return o.AccessTokenDescription, true
}

// HasAccessTokenDescription returns a boolean if a field has been set.
func (o *V1NetworkAuthAccessTokensCreateRequest) HasAccessTokenDescription() bool {
	if o != nil && o.AccessTokenDescription != nil {
		return true
	}

	return false
}

// SetAccessTokenDescription gets a reference to the given string and assigns it to the AccessTokenDescription field.
func (o *V1NetworkAuthAccessTokensCreateRequest) SetAccessTokenDescription(v string) {
	o.AccessTokenDescription = &v
}

func (o V1NetworkAuthAccessTokensCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["permissions"] = o.Permissions
	}
	if true {
		toSerialize["access_token_expiration"] = o.AccessTokenExpiration
	}
	if true {
		toSerialize["access_token_name"] = o.AccessTokenName
	}
	if o.AccessTokenDescription != nil {
		toSerialize["access_token_description"] = o.AccessTokenDescription
	}
	return json.Marshal(toSerialize)
}

type NullableV1NetworkAuthAccessTokensCreateRequest struct {
	value *V1NetworkAuthAccessTokensCreateRequest
	isSet bool
}

func (v NullableV1NetworkAuthAccessTokensCreateRequest) Get() *V1NetworkAuthAccessTokensCreateRequest {
	return v.value
}

func (v *NullableV1NetworkAuthAccessTokensCreateRequest) Set(val *V1NetworkAuthAccessTokensCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NetworkAuthAccessTokensCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NetworkAuthAccessTokensCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NetworkAuthAccessTokensCreateRequest(val *V1NetworkAuthAccessTokensCreateRequest) *NullableV1NetworkAuthAccessTokensCreateRequest {
	return &NullableV1NetworkAuthAccessTokensCreateRequest{value: val, isSet: true}
}

func (v NullableV1NetworkAuthAccessTokensCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NetworkAuthAccessTokensCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
